### ISSUE TITLE
How to disable page breadcrumbs

### ISSUE THREAD

**Issue by thebergamo** [NotionX/react-notion-x#105]
This is rather a question than an issue. I'm enjoying very much this lib and the template that you provided :)

But, while I'm trying to do some customization, I'm facing an issue towards remove the breadcrumbs to be shown, this is probably reasonable to show to keep as close as possible the idea from Notion, but in my case for example I would like to not show it or have a better control on how I would like to render them.

Thank you again and continue the awesome work :)

**Comment by pbteja1998** [comment]
May be i am wrong, but the only way to remove the breadcrumbs as far as I know is through CSS. You just target `notion-header` class and set the `display` to `none`. Atleast, that's what I am doing.

**Comment by thebergamo** [comment]
Yeah, I had to do that in other components not only css tricks

**Comment by iNorthIsle** [comment]
it it possible to let the the notion-header be the  optional props of NotionRenderer? some cases dont need to show the notion-header, just need to show the content :thinking:

**Comment by hcorta** [comment]
@thebergamo @iNorthIsle I got a similar case. I think that adding the option to pass a custom header component that receives the same props/components but allows for custom representations could solve any case scenario. 

I created this issue to ask whether it makes sense this option:
https://github.com/NotionX/react-notion-x/issues/179

**Comment by hcorta** [comment]
@thebergamo @iNorthIsle I created a PR with a proposal for fully customising the header component #180

**Comment by iNorthIsle** [comment]
> 

That`s great! leave some Nit comments about #180

**Comment by transitive-bullshit** [comment]
You can now set `header={null}` as of #180 which should resolve this.
