### ISSUE TITLE
Callouts can have any kind of data in them now.

### ISSUE THREAD

**Issue by normdoow** [NotionX/react-notion-x#111]
Looks like we have something to update!
https://twitter.com/NotionHQ/status/1420434034744692738

**Comment by osbre** [comment]
Maybe it's just a visual change? because technically callouts always had a "content" property. (to render child blocks)

**Comment by MichaelDevC** [comment]
@normdoow I've just made a pull request for that!

Check it out: #114

**Comment by normdoow** [comment]
Awesome @MichaelDevC. I'll check it out!

**Comment by normdoow** [comment]
This had been added here: https://github.com/NotionX/react-notion-x/pull/114#pullrequestreview-724630398
