### ISSUE TITLE
Board rendered as a Linked database is not being rendered. NotionAPI collectionQuery error Cannot set property 'group_by' of undefined

### ISSUE THREAD

**Issue by pbteja1998** [NotionX/react-notion-x#113]
Related to: `issue` #104 and `PR` #107

---

Hi,

The problem with the rendering of board views seems to have resurfaced. After trying out a few different things, this only seems to happen for boards created as linked databases. If I inline a board inside a page, it is getting rendered properly.

---

Link to a Demo Page: https://notion.so/58a2cd864a5a44659f5635f2b4e05545

**Error:**
- NotionAPI collectionQuery error `Cannot set property 'group_by' of undefined`
- skipping missing collection view for block 

Can [this](https://github.com/NotionX/react-notion-x/pull/107/files#diff-730f034e11dd4199e0434acf6897a2b1cb0642641b160fd1c5be24753fda487eR333) be the problem?

**Comment by transitive-bullshit** [comment]
This seems to still be an issue.

**Comment by transitive-bullshit** [comment]
Tracking this in #260
