### ISSUE TITLE
How do I get authToken?

### ISSUE THREAD

**Issue by paulofaria** [NotionX/react-notion-x#115]
Hello, I want to render private pages, but I don't know where/how to get the authToken mentioned in the readme. Could anyone point me in the right direction?

**Comment by pascalvaccaro** [comment]
I was having the same issue, turns out it's not the authToken you need, but your authentication cookie.
Sign-in to Notion in any browser, open your dev tools > Application > Cookie > and copy/paste the `token_v2` cookie value.

**Comment by transitive-bullshit** [comment]
Thanks @pascalvaccaro.

Closing as stale.

**Comment by zwily** [comment]
Sorry for adding a question on a closed issue... Doesn't this auth cookie only last a short amount of time?

**Comment by Reomar** [comment]
> Sorry for adding a question on a closed issue... Doesn't this auth cookie only last a short amount of time?

Did you find any solutions?

**Comment by wythh24** [comment]
> > Sorry for adding a question on a closed issue... Doesn't this auth cookie only last a short amount of time?
> > @zwily
> 
> Did you find any solutions?

https://github.com/NotionX/react-notion-x?tab=readme-ov-file#private-pages
