### ISSUE TITLE
Feature Request: Adding Click to Copy button

### ISSUE THREAD

**Issue by limdh0827** [NotionX/react-notion-x#116]
How about adding the _**click to copy**_ button to the code block component? 

e.g. 
![스크린샷 2021-08-08 오전 11 50 36](https://user-images.githubusercontent.com/56031076/128619158-8249b7f8-0345-4904-9301-18b3ab55ca30.png)

Or can I use the custom code block component? Thank you 🙏

**Comment by transitive-bullshit** [comment]
Done :) https://github.com/NotionX/react-notion-x/pull/239
