### ISSUE TITLE
Unable to access private resources anymore

### ISSUE THREAD

**Issue by ddanielcruzz** [NotionX/react-notion-x#117]
Hey there, 

Do you know if there were any changes to Notion's API? I got a blog with private pages working for some time, and out of nowhere it stopped working. I realized that I the problem is that I can't access private resources. I get the error `Notion page not found "..."`. 

If I change the page to public it works. I already tried updating my `token_v2`. 

Thanks!

**Comment by ddanielcruzz** [comment]
After some research, it seems that now you also need to pass the active user to the constructor like: 

```js
const notion = new NotionAPI({
    authToken: token_v2,
    activeUser: notion_user_id,
  });
```

Idk if that's needed for everyone trying to access private resources.

**Comment by transitive-bullshit** [comment]
Hey Daniel, yep this is required for accessing private resources with this library. The default instructions assume that you've made your page(s) publicly accessible to the web.

**Comment by ddanielcruzz** [comment]
Is it ok if I make a PR to add/update the instructions for private resources?

**Comment by transitive-bullshit** [comment]
@ddanielcruzz that'd be awesome 🙂

**Comment by madooei** [comment]
@ddanielcruzz thanks for doing this; I had the same problem. Moreover, it was not at all obvious to me that `token_v2` is not the Notion API token (thanks to #115). Please note this information in your instructions. Thanks again.

**Comment by tdurieux** [comment]
@ddanielcruzz even by adding token_v2 and notion_user_id is not working. 
It was working fine a few weeks ago but not anymore. Am I the only one in this case?

**Comment by louisbarclay** [comment]
> Is it ok if I make a PR to add/update the instructions for private resources?

@ddanielcruzz Did you get round to this? Could you share some tips on how you constructed authToken?

I have a public Notion integration and need to go from a secret key provided for a user by going through the Notion OAuth flow [as described here](https://developers.notion.com/docs/authorization) (in format secret_rAnDoMhAsH) to getting a token which works with react-notion-x.

Getting this from a cookie is not an option (i.e. as seen in [#115](https://github.com/NotionX/react-notion-x/issues/115)).

**Comment by louisbarclay** [comment]
Think I am understanding that this is likely an impossible request - you almost certainly can't get the kind of authToken that works with react-notion-x from a secret key that a user provides to a public integration.

**Comment by transitive-bullshit** [comment]
Closing as stale.
