### ISSUE TITLE
Error while installing dependencies

### ISSUE THREAD

**Issue by beevk** [NotionX/react-notion-x#120]
I just cloned the repo and switched to the example directory.

```shell
    npm i
```
This gives _unable to resolve dependency tree_ error. This happens because react-notion-x has peer dependency on react and the version doesn't match. Please fix it.

**Comment by beevk** [comment]
Please update the React version to 17.0.2 so it can be used with NextJS 11.

**Comment by MichaelDevC** [comment]
Try installing packages with `npm i --legacy-peer-deps`

**Comment by transitive-bullshit** [comment]
This should be fixed in v6.

Note: this repo uses `yarn` workspaces so you have to run `yarn` once at the root before starting.

After that, you can run `yarn dev` or `yarn build` from any of the example directories.
