### ISSUE TITLE
Version mismatch - React

### ISSUE THREAD

**Issue by beevk** [NotionX/react-notion-x#122]
I see [here](https://github.com/NotionX/react-notion-x/blob/0c473919e9162c46c75f82e6f5578247e66b9e78/packages/react-notion-x/package.json#L38) that the package has dev dependency on @types/react with version 17. But the [peer dependency](https://github.com/NotionX/react-notion-x/blob/0c473919e9162c46c75f82e6f5578247e66b9e78/packages/react-notion-x/package.json#L46) still suggests React 16+. Please update peer dependency to React 17 as well.

**Comment by transitive-bullshit** [comment]
The peer deps for v6 require react >= 16. There's no point that I can see in being stricter than that unless somebody has a reproducible issue caused by it.

Not everyone can upgrade react right away depending on their environment.
