### ISSUE TITLE
Support for Custom Image Component

### ISSUE THREAD

**Issue by beevk** [NotionX/react-notion-x#126]
Hi, I noticed the library supports custom components for few elements like the link, code, etc. I wanted to use a Custom component for images. This might be useful if I want to use responsive images by hosting them on my S3 and modifying the path for a different image. But the library currently doesn't support that.

Is it something that you'll be interested to add to the library? Or will you accept a pull request if I add this feature to the library? However, I'm not sure how to proceed with this so might need a little bit of help there.

**Comment by beevk** [comment]
Hello, any update?

**Comment by transitive-bullshit** [comment]
This was addressed awhile back, but it was only partial.

v6 adds full support for custom image components, including special support for `next/image`.

Here's an example of using `next/image`: https://github.com/NotionX/react-notion-x/blob/master/examples/full/components/NotionPage.tsx#L115

If you want to use a different custom image component, just pass it to the `components.Image` prop of `NotionRenderer`.
