### ISSUE TITLE
Optional components contribute to JS size even when not used

### ISSUE THREAD

**Issue by shueja-personal** [NotionX/react-notion-x#131]
Hello,
I’m using transitiveBullshit next-js-notion-starter-kit, and trying to optimize in LightHouse. I noticed that my biggest unused JavaScript chunk (320 on) has been what looks to be React-Notion-X’s components from third-party.tsx, which I haven’t opted into or passed into NotionRenderer but is being loaded likely in the line 
‘import {NotionRenderer} from ‘react-notion-x’
Is there a better import path than index.tsx that won’t load the third-party heavy components?

**Comment by shueja-personal** [comment]
More info
![image](https://user-images.githubusercontent.com/32416547/133357478-ca549f8d-4205-4033-baef-c52fcf1865b3.png)
Here's the bundle-analyzer, and as you can see, the PDF stuff carries with it a lot of overhead even when not used. The minified pdfjs chunks together take up around 1 MB parsed size (if I understand this tool correctly). When I removed all imports to react-notion-x, those disappeared. When I then brought back just the NotionRenderer import, without using NotionRenderer elsewhere, the pdfjs chunks remained gone. As soon as I imported Collection dynamically * , the chunks were back.


* 
```
const Collection = dynamic(() =>
  import('react-notion-x').then((notion) => notion.Collection)
)
```

**Comment by transitive-bullshit** [comment]
v6 has finally addressed this in a way that is guaranteed to solve the problem regardless of how the consuming application is built.

We're now using `tsup` and `esbuild` to create separate bundles for each of the optional components.

See here for a full working example: https://github.com/NotionX/react-notion-x/tree/master/examples/full
