### ISSUE TITLE
Not working with Create-React-App

### ISSUE THREAD

**Issue by eddyhdzg** [NotionX/react-notion-x#138]
Is there any **_working_** example of react-notion-x working with CRA?

**Comment by Turokhunter** [comment]
Ran into the same problem. Seems to be connected to the way webpack is set up for create-React-App.

`
Compiled with problems:X

ERROR in ./node_modules/@szmarczak/http-timer/dist/source/index.js 9:15-30

Module not found: Error: Can't resolve 'util' in '/Users/turokhunter/Dropbox/Personal/Website/portfolio/node_modules/@szmarczak/http-timer/dist/source'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it. 
`

**Comment by enpitsuLin** [comment]
Because many of the dependencies of this `notion-client` only run in the node environment, there is no browser-based usage

But you can make your own package based on `notion-type` and `notion-utils`

**Comment by transitive-bullshit** [comment]
This has been fixed with v6 (I tested it locally). 💪
