### ISSUE TITLE
Collection Views Not working anymore

### ISSUE THREAD

**Issue by normdoow** [NotionX/react-notion-x#139]
Notion made a  change  with their api today that is breaking the collections endpoint.

This is the endpoint `https://www.notion.so/api/v3/queryCollection`

I'm looking into this to try to make a fix currently. If you think you know what the change should be, let me know!

**Comment by normdoow** [comment]
Fixed mostly in v4.9.2  https://github.com/NotionX/react-notion-x/pull/140. Board views still  need a little work to fix.

**Comment by pzjzeason** [comment]
Build error:

Type 'CodepenBlock' is missing the following properties from type 'CollectionViewPageBlock': collection_id, view_ids, permissions.

**Comment by normdoow** [comment]
> Build error:
> 
> Type 'CodepenBlock' is missing the following properties from type 'CollectionViewPageBlock': collection_id, view_ids, permissions.

This is when your building the example?

**Comment by normdoow** [comment]
@pzjzeason  Looks like notion-types version is up to date on the latest.

**Comment by seonglae** [comment]
Can't find collection with released web app and can't build anymore app with error
```
info  - Collecting page data ...NotionAPI collectionQuery error Cannot read property 'type' of undefined
```

My [proxy notion app](https://doc.seongland.com/46fa1b6d1f7e4297b85d8ff0b27fc803) shows collection
but [react-notion-x](https://next.seongland.com/46fa1b6d1f7e4297b85d8ff0b27fc803) not showing collection
