### ISSUE TITLE
Whenever I click on image, I get an error relating to the zoomContainer being null. 

### ISSUE THREAD

**Issue by donmorton** [NotionX/react-notion-x#15]
![Screen Shot 2021-01-24 at 4 11 41 PM](https://user-images.githubusercontent.com/5582036/105648203-1dcfe500-5e5f-11eb-87f6-a000418af40e.png)

Whenever I click on image, I get an error relating to the zoomContainer being null. 

"TypeError: null is not an object (evaluating 'zoomContainer.getBoundingClientRect')"

The notion page id I am rendering: 8e7024e994cb425fb70429e7b20915ff

My code 
```
      <Container>
        <Center>
          <NotionRenderer
            recordMap={recordMap}
            fullPage={false}
            darkMode={false}
          />
        </Center>
      </Container>
```

I know the expected behavior is that the image pops up in a zoomed form. Not sure what I am doing wrong here. Any advice?

**Comment by transitive-bullshit** [comment]
Ahhh this is due to a recent change since I haven't tested `fullPage={false}` as much.

It's looking for `.notion-viewport` and not finding it.

Let me work on a solution.

**Comment by transitive-bullshit** [comment]
If you install the most recent version `v3.3.3`, it should work for you now.

**Comment by donmorton** [comment]
thanks so much @transitive-bullshit !!
