### ISSUE TITLE
Get PDF support working again

### ISSUE THREAD

**Issue by transitive-bullshit** [NotionX/react-notion-x#153]
There are numerous build issues with `react-pdf` and Next.js.

See https://github.com/wojtekmaj/react-pdf/issues/136 and https://github.com/wojtekmaj/react-pdf/issues/874 for the two main ones I'm running into.

I've decided to remove `react-pdf` from `react-notion-x` for now until these issues are sorted.

**Comment by herohoro** [comment]
We look forward to PDF support.(´；ω；｀)

**Comment by transitive-bullshit** [comment]
This should be working again as of `v4.19.0`.

I also added an example of how to use pdfs: https://github.com/NotionX/react-notion-x/blob/master/examples/full/components/NotionPage.tsx#L31

**Comment by herohoro** [comment]
Thank you very much. I will update it as soon as possible.
