### ISSUE TITLE
Collection Views not showing when inside a toggle

### ISSUE THREAD

**Issue by normdoow** [NotionX/react-notion-x#156]
Example page of the issue: a899b98b7cdc424585e5ddebbdae60cc

I tried to get to the bottom of this. I couldn't figure out a fix but this is what I found.

The `getPageRaw` function for calling the `loadPageChunk` endpoint is not returning collection data from Notion when a collection is inside a toggle. But when it is outside it does contain the collection data.

Viewing how Notion works with this. It looks like Notion makes a second call to the `loadPageChunk` after the page loads. This call does return the collection data that is needed. Oddly enough the second call uses the exact same parameters as the first.

Sometimes Notion doesn't make the call till the user opens the toggle and then the table dynamically loads.

Not sure how we should handle this.

**Comment by Dmitry-zh** [comment]
Hello! This text was prepared with google translate, so I apologize in advance.

I use your project in conjunction with nextjs-notion-starter-kit, so I solved this problem in another way - a lazy request from the client side.
Do not judge strictly by the code, it's still a draft:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/62336121/157447659-105ff24d-4110-46f9-964e-4a2d8524e074.png">

LazyBlock.tsx

<img width="956" alt="image" src="https://user-images.githubusercontent.com/62336121/157447753-f92f268e-6c00-4c63-a353-96260197c4da.png">

And /api/get-block makes a request from the server side of the application.


P.S. I understand that this is not a solution for the architecture of this project, but perhaps this will lead to a certain idea.

**Comment by transitive-bullshit** [comment]
Closing as not planned.
