### ISSUE TITLE
Do we implement search ourselves? Any working examples?

### ISSUE THREAD

**Issue by on2air** [NotionX/react-notion-x#165]
From what I can see, it appears we implement the search function ourselves, is that correct?

Im not seeing any example of how to implement that. 

Is that correct?  Just want to make sure I'm not missing something before I implement that.

**Comment by hcorta** [comment]
Hi @on2air the **notion-client** already includes the search functionality.

You may use it like this: 
```
const api = new NotionAPI()
const output = await api.search({
      query: <string>,
      ancestorId: <pageId>
    })
```

Hope that helps.

**Comment by transitive-bullshit** [comment]
The default search params have been fixed in v6. Notion changed how they handle `isNavigableOnly`.

@hcorta's example is correct.

**Comment by tomcurphey** [comment]
Hi Travis
Can you please provide a more specific answer?

Below I have pasted the "Search Function" your team provides, I'm getting cors errors..
Where do I add the Notion_Key to get this to work?
Also on your Youtube example, it has the same issue
https://www.notion.so/recipe-revenue/Notion-Built-Website-c59b66246c074fa8b4d6a9f7a8780916

`// import ky from 'ky'
import fetch from 'isomorphic-unfetch'
import pMemoize from 'p-memoize'

import { api } from './config'
import * as types from './types'

export const searchNotion = pMemoize(searchNotionImpl, { maxAge: 10000 })

async function searchNotionImpl(
  params: types.SearchParams
): Promise<types.SearchResults> {
  return fetch(api.searchNotion, {
    method: 'POST',
    body: JSON.stringify(params),
    headers: {
      'content-type': 'application/json'
    }
  })
    .then((res) => {
      console.log(res)

      if (res.ok) {
        return res
      }

      // convert non-2xx HTTP responses into errors
      const error: any = new Error(res.statusText)
      error.response = res
      return Promise.reject(error)
    })
    .then((res) => res.json())

  // return ky
  //   .post(api.searchNotion, {
  //     json: params
  //   })
  //   .json()
}
`
