### ISSUE TITLE
Support for simple tables

### ISSUE THREAD

**Issue by MartinXPN** [NotionX/react-notion-x#166]
In one of their latest releases, the Notion team released a feature that adds support for simple tables. This blogpost describes the feature in more details: https://www.notion.so/guides/simple-tables-vs-databases

Currently, when loading a page containing a simple table, `react-notion-x` does not render anything and the space for the table is completely empty. 

Are there plans to support the newly added feature?

Thanks for your work and the great library!

**Comment by thanhlmm** [comment]
Yeah, I'm also waiting for simple table supported

**Comment by normdoow** [comment]
If someone wanted to add a PR for this, that would be great!

**Comment by normdoow** [comment]
Live for v4.14.0

**Comment by MartinXPN** [comment]
Seems like all the styles are completely off after upgrading.
All the code blocks, headings, etc used to render completely fine, but all of them lost their styling after the upgrade. 
Am I missing something?

**Comment by normdoow** [comment]
> Seems like all the styles are completely off after upgrading. All the code blocks, headings, etc used to render completely fine, but all of them lost their styling after the upgrade. Am I missing something?
> 
> The last version I was using was v4.11.0

Hmm maybe. Make sure you are updating all the packages. notion-types, notion-utils, notion-client, and react-notion-x to v4.14.1 (.1 has a fix for default tables).

**Comment by MartinXPN** [comment]
Yeah, you were right, `yarn remove`-ing the package and then `yarn add`-ing it resolved the issue.
Thanks!
