### ISSUE TITLE
Support for custom header?

### ISSUE THREAD

**Issue by hcorta** [NotionX/react-notion-x#179]
Hi @normdoow!
I wonder if it would make sense to add the option to pass a custom header component, the same way a footer component can be passed as props.

`
      <NotionRenderer
        {...rest}
         header={<CustomHeader />}
      />
`

If so, I'd be willing to implement it 🙂
Thanks

**Comment by normdoow** [comment]
Hey, good idea! I think we have a PR up that should allow this. Could you take a look at it and give some feedback?
Would this fulfill your needs?
https://github.com/NotionX/react-notion-x/pull/171

**Comment by hcorta** [comment]
@normdoow I have created this PR #180 extending in some aspects @harajune's proposal, which was a very good inspiration. Hope it helps.
