### ISSUE TITLE
Uploaded custom images not rendering

### ISSUE THREAD

**Issue by cyrus25** [NotionX/react-notion-x#184]
Uploaded custom cover images and images on the notion page are not being rendered for private resources. Opening image URL in new tab gives this error-
`{
"errorId": "5cda0c3a-8285-429f-9f1e-82fb9df1356c",
"name": "ValidationError",
"message": "User does not have access."
}` 
 I am able to render the other content of the notion page.

**Comment by transitive-bullshit** [comment]
This should be fixed as long as you're using `signedUrls` and the uploaded images are publicly accessible.

Here's an example page showing it in action: https://react-notion-x-demo.transitivebullsh.it/912379b0c54440a286619f76446cd753
