### ISSUE TITLE
Hash link in single page application

### ISSUE THREAD

**Issue by hlehmann** [NotionX/react-notion-x#185]
When using react-notion-x in a single page application with `<base href="/" />`

Hash link like `<a href={"#id"}>{title}</a>` will link to `/#id` instead of `/my-page#id`.

Could we have a `mapHashlinkUrl` like the `mapPageUrl` or include absolute location to the hash link to solve this ?

**Comment by transitive-bullshit** [comment]
The best way to handle this is to override the `mapPageUrl` prop to `NotionRenderer`.

See the default implementation to get started: https://github.com/NotionX/react-notion-x/blob/97b06948ad99101f9c61d3aef3328dcc91371f2a/packages/react-notion-x/src/utils.ts#L86
