### ISSUE TITLE
Code blocks not rendering?

### ISSUE THREAD

**Issue by Commandtechno** [NotionX/react-notion-x#193]
I was testing different things in this package and noticed code blocks weren't rendering, I tried it on code sandbox in case it was an issue with what I was using and was able to reproduce it. I'm not really sure why this is happening or whats going on, but the elements just aren't being rendered. The page response contains the code elements, but they just aren't being rendered in the HTML.

Notion: https://react-notion-x-demo.transitivebullsh.it/code-blocks-0c322c33381c49bca5083a451c334c39
CodeSandbox: https://codesandbox.io/s/distracted-river-3udil

recordMap with code block
![image](https://user-images.githubusercontent.com/68407783/150047778-528a3672-b380-4ef6-9d2f-eaa1e08dd75f.png)

HTML where code block should be
![image](https://user-images.githubusercontent.com/68407783/150047854-ffb7961f-f01c-4b3c-bb4c-5f2fdf8cb11a.png)

**Comment by futantan** [comment]
You need to import code from react-notion-x and add it to components of NotionRenderer

**Comment by 0815pascal** [comment]
This is how I managed to make it work: 

```
<NotionRenderer
                rootPageId={"XXXXX"}
                recordMap={data}
                fullPage={true}
                darkMode={false}
                components={{
                    code: Code,
                    collection: Collection,
                    collectionRow: CollectionRow
                }}
            />
```

**Comment by Commandtechno** [comment]
Ah, I see, I could only find how to do this from the source.
Really feels like something that should be mentioned in the README or something since its a core feature that just doesn't work unless you do that.

Thanks though!
