### ISSUE TITLE
How do I use math and code blocks?

### ISSUE THREAD

**Issue by cfranc0** [NotionX/react-notion-x#20]
I was trying to figure out why my quick app using react-notion-x was not displaying formulas.

I decided to use the live test version of the app at
[https://react-demo.notionx.so/3d7df5e4a14141c9932465a0aa394217](https://react-demo.notionx.so/3d7df5e4a14141c9932465a0aa394217)
and discovered the page correctly working.

I then cloned this repository on my local machine, browsed to the test dir, installed dependencies via `npm i` and ran `npm run dev`.
When I browse to the same page as before, now on my local machine at
http://localhost:3000/3d7df5e4a14141c9932465a0aa394217
the page is missing formulas, tables and code blocks.

Console was saying
![image](https://user-images.githubusercontent.com/20073894/106395469-b7b90400-6402-11eb-903b-66a8cce6aeb7.png)

The original Notion page is available at [this link](https://www.notion.so/Export-test-3d7df5e4a14141c9932465a0aa394217).

**Comment by transitive-bullshit** [comment]
Hey @cfranc0, this is due to a recent change that I haven't updated the docs for yet.

Heavier components like Katex, equations, pdfs, and collections are all loaded opt-in so that the base `NotionRenderer` export isn't bloated with optional components.

**Comment by transitive-bullshit** [comment]
To solve this, you'll need to explicitly import the Equation and add it to `NotionRenderer`'s `components` prop.

Here's a live example (doesn't use equations, but does use other lazy components): https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/components/NotionPage.tsx#L204-L234

```tsx
import { Equation } from `react-notion-x`

// ...

<NotionRenderer components={{ equation: Equation }} />

```

**Comment by cfranc0** [comment]
That's awesome! Thanks so much!

**Comment by cfranc0** [comment]
May I suggest to also allow for the medium-zoom behavior for images to be opt-in?

**Comment by transitive-bullshit** [comment]
Yeah -- that's a great idea. Would you mind opening a separate issue to track?
