### ISSUE TITLE
incorrect peer dependency

### ISSUE THREAD

**Issue by zyj1022** [NotionX/react-notion-x#200]
warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
warning "react-notion-x > react-pdf > pdfjs-dist@2.10.377" has unmet peer dependency "worker-loader@^3.0.7".

**Comment by transitive-bullshit** [comment]
Just released a major update with v6. If you're still having issues with install warnings, please open a new issue with more info. Thx!
