### ISSUE TITLE
incorrect color type: `teal` should now be `green`, and no `default`

### ISSUE THREAD

**Issue by enpitsuLin** [NotionX/react-notion-x#202]
Notice that the green color is not displayed correctly in use, maybe i should open pr to replace `teal` to `green` ?
anyone has some suggestions?
![Snipaste_2022-01-26_21-03-59](https://user-images.githubusercontent.com/29378026/151168240-118554d8-651e-4258-bfab-58ddf70219e1.png)

**Comment by AakashMallik** [comment]
Yes, this needs to be addressed. Can you create a PR for this? Do we have other dependencies on the class `color-teal` anywhere else?

**Comment by transitive-bullshit** [comment]
Please follow the issue template and include a notion ID to make it easier for me to repro.

All notion blocks have a `version` property which we can ignore most of the time, but [this page for example](https://react-notion-x-demo.transitivebullsh.it/54bf56611797480c951e5c1f96cb06f2), shows that under the hood "green" is still referenced by the API as "teal" — at least for some block versions.
