### ISSUE TITLE
Can I Use <Image /> for Next.js next/image

### ISSUE THREAD

**Issue by ShaikRehan123** [NotionX/react-notion-x#203]

**Comment by transitive-bullshit** [comment]
Yes, this was introduced in https://github.com/NotionX/react-notion-x/pull/158

@normdoow would be great to add docs and an example of how to do this to make it more clear.

**Comment by ShaikRehan123** [comment]
Yes can I FInd docs for how to use it

**Comment by ShaikRehan123** [comment]
I am closing this because @normdoow might be busy

**Comment by eagor** [comment]
you can find example here: https://github.com/NotionX/react-notion-x/blob/master/example/pages/%5BpageId%5D.tsx#L71
( just use `<Image>` instead of `<img>`)
also, make sure to set `customImages={true}`
