### ISSUE TITLE
Fresh build - Server Error: The default export is not a React Component in page: "/_error" via Warning: React.jsx: type is invalid

### ISSUE THREAD

**Issue by agileben** [NotionX/react-notion-x#213]
Hi, 

Total newbie to next and react so this is probably something obvious:

I did a clean checkout and build gives me this error on yarn run dev:

Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at index.tsx:21.
    at NotionDomainPage
    at App (webpack-internal:///./pages/_app.tsx:81:3)
    at AppContainer (/home/runner/nextjs-notion-starter-kit/node_modules/next/dist/server/render.js:293:29)
    
Feel free to join my replit to see the error:  https://replit.com/join/xjnewcyemy-agileben

**Comment by transitive-bullshit** [comment]
Not sure exactly what you were running into, but a lot has changed in v6. Closing now as the packaging and exports are all different.
