### ISSUE TITLE
Gatsby support?

### ISSUE THREAD

**Issue by ISnackable** [NotionX/react-notion-x#214]
Does this work with GatsbyJS?

I know this is a React renderer for Notion but I noticed the README mentioned that heavier components like PDFs and collection views **can** be loaded lazily via `next/dynamic`. Does that mean this renderer will work with GatsbyJS?

**Comment by enpitsuLin** [comment]
I think it will work with gatsby

try [createPages](https://www.gatsbyjs.org/docs/node-apis/#createPages) with a template which contain renderer  block

**Comment by ISnackable** [comment]
Thanks, you might be right! However, I decided to rewrite my site in NextJS instead.

Closing this issue. Hopefully this issue helps others in the future.
