### ISSUE TITLE
Cannot enough information about notion page url 

### ISSUE THREAD

**Issue by futantan** [NotionX/react-notion-x#218]
Describe the bug
For the custom pageLink component, we can't get enough information to get the final URL of the notion page.

Expected behavior
I'd like to open its original notion URL in a new tab.

**Comment by ntcho** [comment]
Have you tried not passing the `pageLink` component via the `components` property?

I think it will default to the original Notion URL without it.

**Comment by transitive-bullshit** [comment]
@futantan I think you want to override `mapPageUrl` and then use the result from within a custom `pageLink`.
