### ISSUE TITLE
Adjust column width ratio according to the original page

### ISSUE THREAD

**Issue by cfranc0** [NotionX/react-notion-x#22]
I think this library would be even better if the column width ration reflected what's set in Notion.
The API provides the ratio value for columns types
![immagine](https://user-images.githubusercontent.com/20073894/106511427-80188d80-64d0-11eb-9d93-b26391fab461.png)

This is the original Notion page (taken from the example page)
![immagine](https://user-images.githubusercontent.com/20073894/106511863-22d10c00-64d1-11eb-99b5-1edae20ea4ae.png)
Gets turned into this
![immagine](https://user-images.githubusercontent.com/20073894/106511907-31b7be80-64d1-11eb-98c0-86ccdc675ca3.png)

This feature is particularly important when dealing with pictures because they try to expand as much as possible, crushing the other columns.

**Comment by transitive-bullshit** [comment]
Thanks for bringing this up @cfranc0. I was just messing around with this last week and probably introduced an issue.

My goal for `react-notion-x` is to match Notion formatting as closely as possible, and then customize that formatting to be a bit more stylized in certain areas with the [Next.js starter kit](https://github.com/transitive-bullshit/nextjs-notion-starter-kit).

**Comment by cfranc0** [comment]
I have to be honest here, your work so far has been fantastic!
This is definitely the most complete Notion-like package out there and I'm sure it has the potential to power so many future projects.
Personally I'm not advanced enough with my JS skills to be able to contribute directly but I would love to do so in the future.

> 
> 
> Thanks for bringing this up @cfranc0. I was just messing around with this last week and probably introduced an issue.
> 
> My goal for `react-notion-x` is to match Notion formatting as closely as possible, and then customize that formatting to be a bit more stylized in certain areas with the [Next.js starter kit](https://github.com/transitive-bullshit/nextjs-notion-starter-kit).

**Comment by transitive-bullshit** [comment]
Much appreciated @cfranc0. Would love to help you contribute if there are specific areas you're interested in.

One thing that you can do even without much JS knowledge is to share the project & spread the word 😄
