### ISSUE TITLE
C++ code snippet is not rendered properly

### ISSUE THREAD

**Issue by MartinXPN** [NotionX/react-notion-x#220]
Seems like the latest notion API returns the language as `C++` in the `blocks`. Yet, when rendering the snippet, the language should be cpp in the html resulting in `language-cpp`. That inconsitency causes the c++ snippets to not being rendered properly. 

I haven't checked for other languages, but seems like there might be other language names that might have a similar issue cased by inconsistency between libraries.

**Comment by frempongandrews** [comment]
yeah, javascript snippet doesn't show up

**Comment by transitive-bullshit** [comment]
Fixed in v6
