### ISSUE TITLE
Create util for converting official API response to recordMap

### ISSUE THREAD

**Issue by trevorwhealy** [NotionX/react-notion-x#228]
Notion now has an official API that is easy to use.

The React renderer component of this package is the **best** but requires the unofficial API workaround.

Here's how easy it is to get the blocks using the official Notion API today:

```
const { results: blocks, next_cursor } = await notion.blocks.children.list({
   block_id: blockId,
});
```

Which yields this an array of this response shape:
```
archived: boolean
created_by: {}
created_time: date
has_children: boolean
id: string
last_edited_by: {}
last_edited_time: date
object: "block"
paragraph: {}
type: string
```

But the API client provided in this package fetches `blocks` from the unofficial `loadPageChunk`
Which yields a normalized object of blocks that have a completely different structure.

```
fetch(loadPageChunk, {
   pageId, chunkNumber: 0, verticalColumns: false, limit: 100, cursor: { stack: []} }
}
```

I believe this is going to lead to even more new React Notion renderers being created like this:
- https://github.com/9gustin/react-notion-render/

Exposing a utility like `createRecordMap` that takes the official response and creates the normalized data structure that is expected by the renderer will be a great addition for those of us that cannot use the third party workaround.

**Comment by transitive-bullshit** [comment]
I think this is a great idea.

There have been a lot of people asking for it, and when `react-notion-x` was first developed it wasn't an option. The official API is lacking a lot in terms of block support, but I can completely understand the desire to integrate with the official API and the additional use cases it entails.

Not sure I'll be able to get to this, but if anyone wants direction for how to approach things, feel free to ask.

Here's a link to my previous thoughts on the state of notion's official API: https://github.com/NotionX/react-notion-x/issues/92#issuecomment-964615906

See also #66 and #173
