### ISSUE TITLE
Is there a way to find the owner of content?

### ISSUE THREAD

**Issue by mankins** [NotionX/react-notion-x#237]
I haven't been able to determine if there's a way to find the `owner id` of a particular post.

For instance it would be nice to be able to allow rendering of a particular set of user's notion pages.

**Comment by transitive-bullshit** [comment]
I think the easiest way to do this would be to add a new column to the collection that manually sets some field you want to filter by.

I'm sure there's a way to do it without doing things manually, but I'm not sure how.

**Comment by transitive-bullshit** [comment]
Here's an example of how I'm doing something similar for my blog posts. See the `Public` property which I'm using to filter on: https://transitive-bs.notion.site/f917892e0b8c4dbeb1743620de57a0ec?v=c70d830fa2ec435d95baa557ac7b333a

**Comment by mankins** [comment]
Thanks for that idea @transitive-bullshit . 

I ended up finding `page.block[key].value.space_id` and comparing it to a static list of spaces.

I'm not sure if this gets modified over time, but it seems to have done the trick. 

```
const ALLOWED_SPACES = ['uuid-here-of-space'];

const pageAllowed = (page) => {
  // see if any page.block[key].value.space_id is in ALLOWED_SPACES
  let allowed = false;
  Object.values(page.block).some(block => {
    if (!allowed && block.value && block.value.space_id) {
      allowed = ALLOWED_SPACES.includes(block.value.space_id);
    }
  });
  return allowed;
};
```
