### ISSUE TITLE
Support for custom component render for "embed" block

### ISSUE THREAD

**Issue by ciiiii** [NotionX/react-notion-x#240]
Is this is in plan or not?

**Comment by transitive-bullshit** [comment]
I think this is a great idea.

We'd want to make sure that the custom embed block had access to the default one so it could fallback.

**Comment by ciiiii** [comment]
> I think this is a great idea.
> 
> We'd want to make sure that the custom embed block had access to the default one so it could fallback.

Maybe we can use `AssetWrapper` as default components for the embed blocks, I will try if this will work fine without any user defined embed component.

**Comment by transitive-bullshit** [comment]
Thanks @ciiiii 😄

**Comment by ciiiii** [comment]
> Thanks @ciiiii 😄

You're welcome, it's a great framework, I like it😍.
