### ISSUE TITLE
Cannot find package 'notion-client' with 6.0.8

### ISSUE THREAD

**Issue by mankins** [NotionX/react-notion-x#241]
I'm building notion-client in a sveltekit app (vite), and noticed that I started to get the error:

```
Cannot find package 'notion-client' 
```

I was able to fix this by reverting back to `4.19.8`...I noticed a flurry of releases in the last few days so thought I'd mention this in case it's helpful. 

I'm on `node v16.14.0`.

**Comment by mankins** [comment]
I can't completely confirm this, so I'm going to close this. Will reopen with more information if I can confirm.

**Comment by transitive-bullshit** [comment]
Hmmm I think this may be an issue with vscode not finding the typings?

Or was it not building for you?

**Comment by mankins** [comment]
It's building ok, but at runtime gives:

> Cannot find package 'notion-client' imported from /path/here

I was able to reproduce this locally, revert to an earlier version and get the production build working again locally. But then when I pushed to actual production the old error happened... so I think we have some layer caching issue with production we have to work through... Not sure yet, but will update if I find there's actually an error.

**Comment by urbanrotnik** [comment]
@mankins Did you solve this? I have the same problem with the update to 6.x.x when I run `npm start` locally

**Comment by mankins** [comment]
@urbanrotnik I ended up reverting to the last of the `4.x.x` series and it resolved. I haven't had a moment to find the error though. I do think there's likely a bug with something related to esm.

**Comment by mankins** [comment]
I'll reopen this issue for @transitive-bullshit

**Comment by transitive-bullshit** [comment]
@urbanrotnik @mankins can you try with `6.1.0`?

I'm not able to reproduce the issue locally. Could you point me to a minimal repro or provide detailed instructions for how you're installing and running into this error?

Thanks!
