### ISSUE TITLE
Notion API changed, need improvement

### ISSUE THREAD

**Issue by Dmitry-zh** [NotionX/react-notion-x#244]
Previously, to create a link to the table, Notion offered to create linked databas, but now it offers to create linked database view.
Because of this, we get a 400 response on the QueryCollection endpoint.
I will not make a pull request as I doubt that the quality of my code is good

FIX notion-api.ts: 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/62336121/160334170-ffed4c2a-1d9f-414b-ad38-22d3c2833d6e.png">
<img width="662" alt="image" src="https://user-images.githubusercontent.com/62336121/160334210-5e21b0c6-b2a8-4fca-a53a-fc12d9c8b22a.png">

Then, also now we do not always have filters in the query2 property :
FIX notion-api.ts
<img width="734" alt="image" src="https://user-images.githubusercontent.com/62336121/160334447-b27475eb-9638-4e13-8047-fc7c2087928a.png">
<img width="749" alt="image" src="https://user-images.githubusercontent.com/62336121/160334497-d4cb2053-516a-4fac-9022-1fd930b647a2.png">

You can see for yourself by creating a new collection and linking it to another page

Also your notion api doesn't know how to work with pagination
ISSUE: https://github.com/NotionX/react-notion-x/issues/147

Look at this request:
https://www.notion.so/api/v3/loadPageChunk
{
    "pageId": "541c7659-31d7-4e82-9a62-9d0aa7073e0e",
    "limit": 100,
    "cursor": {
        "stack": []
    },
    "chunkNumber": 0,
    "verticalColumns": false
}

It returns cursor -> stack -> { table, id, index }[]
I think it's pagination, when i adding this stack array to request, like this
{
    "pageId": "541c7659-31d7-4e82-9a62-9d0aa7073e0e",
    "limit": 100,
    "cursor": {
        "stack": [[
                {
                    "table": "block",
                    "id": "541c7659-31d7-4e82-9a62-9d0aa7073e0e",
                    "index": 97
                }
            ],
            [
                {
                    "table": "block",
                    "id": "1ffc49f2-faf6-4bf3-90f9-e94dfe059bb0",
                    "index": 0
                }
            ]]
    },
    "chunkNumber": 0,
    "verticalColumns": false
}

and merging this recordmap response with previous response - i get full data about the page!

**Comment by transitive-bullshit** [comment]
This is definitely an area of the code which could use some help.

@Dmitry-zh would you be willing to create a PR?

I'd love to see: a notion page ID that doesn't current work as expected but is fixed after the change.

Thanks!

**Comment by transitive-bullshit** [comment]
Tracking this issue in #260
