### ISSUE TITLE
Google SEO

### ISSUE THREAD

**Issue by istvandesign** [NotionX/react-notion-x#247]
Hello, I have an article that I've published months ago:

https://istvan.design/how-to-recover-a-corrupted-bitlocker-encryption-without-the-recovery-key

Yet there are no signs of it on Google, I've also included the page in the main page at https://istvan.design right in the beginning.

How do you handle SEO with react-notion-x in production ? All elements are blocks of single lines of text, I think this confuses Google's crawler entirely. 

![image](https://user-images.githubusercontent.com/39516661/161033609-8bd26dbf-e110-49c9-9b97-5a7b26676c06.png)

**Comment by transitive-bullshit** [comment]
Hey @istvandesign 👋 

Have you tried submitting your [sitemap](https://istvan.design/api/sitemap.xml) to google? See https://support.google.com/webmasters/answer/7451001

Otherwise, SEO is highly dependent on other pages linking to your site.

For reference, I haven't noticed any issues with SEO on https://transitivebullsh.it once I submitted my sitemap.

**Comment by istvandesign** [comment]
> Hey @istvandesign 👋
> 
> Have you tried submitting your [sitemap](https://istvan.design/api/sitemap.xml) to google? See https://support.google.com/webmasters/answer/7451001
> 
> Otherwise, SEO is highly dependent on other pages linking to your site.
> 
> For reference, I haven't noticed any issues with SEO on https://transitivebullsh.it once I submitted my sitemap.

Thanks for responding so fast, the sitemap could be the issue. However how did you generate your sitemap ?  Did you add https://github.com/iamvishnusankar/next-sitemap ?

**Comment by istvandesign** [comment]
Thanks for responding so fast, I have digged more into the nextjs starter project and found my answer there.

**Comment by transitive-bullshit** [comment]
@istvandesign if you update to the latest, the `/api` is no longer necessary :)
