### ISSUE TITLE
CRA importing third-party components results in an error

### ISSUE THREAD

**Issue by MartinXPN** [NotionX/react-notion-x#250]
I'm using the latest `react-notion-x` version (6.1.2) in my Typescript React project. When importing any of the third-party components like `Code`,  or `Pdf`, the code does not compile:

```shell
Module not found: Error: Can't resolve 'prismjs/components/prism-markup-templating' in '...node_modules/react-notion-x/build/third-party'
Did you mean 'prism-markup-templating.js'?
BREAKING CHANGE: The request 'prismjs/components/prism-markup-templating' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Comment by transitive-bullshit** [comment]
Hey @MartinXPN 👋 

I've definitely seen this before, but I'm not able to reproduce the issue locally.

Would you mind giving me some more info on how you're using `react-notion-x` so I can try to investigate?

- Is there a specific framework you're using?
- What node version?
- If you're using next.js, can you past the output of running `next info`?
- If your code's open source, can you send me a link?

Thanks

**Comment by MartinXPN** [comment]
Sure, it's a React app (created with `create-react-app`. The code is open: https://github.com/MartinXPN/profound.academy/blob/main/src/course/Content.tsx

I haven't pushed the latest version as it was crashing. The difference between the code on the repo and the one I was trying was:
1. I upgraded the `react-notion-x` to the latest on npm
2. Replaced `import {Code, Collection, CollectionRow, Equation, Modal, NotionRenderer} from 'react-notion-x'` with https://github.com/NotionX/react-notion-x#optional-components
3. Replaced `components={{...` in NotionRenderer by `components={{Code, Collection, Equation, Modal, Pdf }}`

**Comment by transitive-bullshit** [comment]
Thanks, Martin.

I've just created an internal [CRA demo](https://github.com/NotionX/react-notion-x/tree/master/examples/cra) and got things working there after a few fixes.

Can you try with `6.2.0`?

**Comment by MartinXPN** [comment]
Works like a charm! Thanks a lot!
Actually, the main bundle size increased by 55KB. I've only used `Code, Collection, Equation, Modal` components (I was using `Code, Collection, CollectionRow, Equation, Modal` before). Is this expected?

**Comment by transitive-bullshit** [comment]
https://bundlephobia.com/package/react-notion-x@4.19.8 is the old version
https://bundlephobia.com/package/react-notion-x@6.3.0 is the new version

The default bundle has been shrunk dramatically.

Third-party components have increased somewhat due to some changes. I think the majority of that 55kb you're seeing is that we're now importing a bunch of default prismjs syntaxes in the third-party code component [here](https://github.com/NotionX/react-notion-x/blob/master/packages/react-notion-x/src/third-party/code.tsx#L12).

**Comment by MartinXPN** [comment]
Makes sense. 

@transitive-bullshit Do you think it can be imported on-prem?
I've done it manually in our project here: https://github.com/MartinXPN/profound.academy/blob/main/src/course/Content.tsx#L59

The main recursive loading logic is defined here: https://github.com/MartinXPN/profound.academy/blob/main/src/course/prismutil.ts#L291

I've basically aggregated all the code languages from notion blocks and loaded them afterwards along with their dependencies.
In the end calling `highlightAll()` from prismjs
