### ISSUE TITLE
Ability to change the default url of Links

### ISSUE THREAD

**Issue by yogeshwaran-ramesh** [NotionX/react-notion-x#253]
Instead of default link `pages/[pageId].tsx ` , Can i open the notion page on `pages/[title]/[pageId].tsx` by clicking notion link.

Below is the Image. when I click the codepen link it should open on `localhost:3000/codepen/:id` instead of `localhost:3000/:id`.

![Screenshot 2022-04-02 at 10 12 12 AM](https://user-images.githubusercontent.com/45158097/161366603-7317b639-cd0a-492b-ac0d-f85fe6c03539.png)

**Comment by transitive-bullshit** [comment]
Yes, this is doable.

You'll need to override the `mapPageUrl` prop of `NotionRenderer`.

See the default implementation here: https://github.com/NotionX/react-notion-x/blob/master/packages/react-notion-x/src/utils.ts#L40
