### ISSUE TITLE
Cannot render Latex Chemical Equations

### ISSUE THREAD

**Issue by e9965** [NotionX/react-notion-x#255]
![image](https://user-images.githubusercontent.com/63435466/161409749-53806ad1-21c7-4df7-95be-8e7053507d97.png)
![image](https://user-images.githubusercontent.com/63435466/161409756-8ba207a1-eed6-4b81-833c-db2c3e134e18.png)

**Comment by transitive-bullshit** [comment]
Please follow the issue template.

E.g., what notion ID can I test this with?

It is working if you're using the library correctly; see here for a demo: https://react-notion-x-demo.transitivebullsh.it/7820b2d5300747b38e31344eb06fbd57

**Comment by tangly1024** [comment]
Hi Devs,
I am trying to render this notion page: [[Public Notion URL]](https://biswadip.notion.site/4925f1b6acbf499b9486148e2be2c5d7?v=94cf7bdf2deb409b9c6662599fd0ab76).
The rendered site with react-notion-x is [[ here ]](https://starter-kit.tangly1024.com/latex-chemical-equation) using the nextjs-notion-starter-kit.

As you can see, the Latex Chemical Equations can not be rendered  correctly.

Thanks in advance!

**Comment by tangly1024** [comment]
would you please reopen this issues? @transitive-bullshit

**Comment by transitive-bullshit** [comment]
Thanks for the repro case @tangly1024.

It definitely looks like a bug.

I'm not sure if this is a bug in our equation handling or in [katex](https://github.com/KaTeX/KaTeX)'s rendering (which is what we're using under the hood to render things).

**Comment by transitive-bullshit** [comment]
Hmmm, it looks like `\ce` and other chemistry-oriented latex features may not be included in `katex` by default. https://github.com/KaTeX/KaTeX/blob/b1311aff1bfeebd75df9389aadfba7a4a697b203/contrib/mhchem/README.md

**Comment by tangly1024** [comment]
Thank you for your help, this solves my questions.

**Comment by transitive-bullshit** [comment]
Closing as resolved. Feel free to replace the default katex `equation` component with a custom one.
