### ISSUE TITLE
Fix & improve collection view support (databases)

### ISSUE THREAD

**Issue by transitive-bullshit** [NotionX/react-notion-x#260]
Notion made a change to their private API a few weeks ago which broke our support for many collection views.

This issue is to track fixing support for these changes, since it's currently spread across multiple issues.

- Older views seem to still work for the most part ([demo](https://react-notion-x-demo.transitivebullsh.it/2fea615a97a7401c81be486e4eec2e94))
- Views created recently have a different data model which we need to support
- Some older views aren't rendering properly like board views
	- Some board views render fine ([example](https://react-notion-x-demo.transitivebullsh.it/ba528cc0a8dd41bcb74c7e9f80a4785d)) but most don't ([example](https://react-notion-x-demo.transitivebullsh.it/2fea615a97a7401c81be486e4eec2e94))

One potential option would be to use the official API for database support (since that's what it's really, really good at), and to use the unofficial API for page content support (since it's much more consistent than the official API in this case https://github.com/NotionX/react-notion-x/pull/256).

The advantage of this approach is that collection support is inherently complex and brittle, so deferring this complexity onto the official API would be great for us.

The downside of this approach is that it would require `react-notion-x` users to use both the official API (with an API key) and the unofficial API, which is a bit awkward.

Would love to hear people's thoughts.

See also #246, #242, #104, #244, #113

cc @normdoow @datduyng @pbteja1998 @biswadipmaity @yogeshwaran-ramesh @TrillCyborg @schickling

**Comment by normdoow** [comment]
I'm working on a hot fix with the unofficial api. Hoping to have that complete by the end of this week if not today. 😅

**Comment by normdoow** [comment]
Implemented here: https://github.com/NotionX/react-notion-x/pull/265

**Comment by ruucm** [comment]
It happens when the group something in the boarder view I think.

https://react-notion-x-demo.transitivebullsh.it/810a38d83ac24a7ebae4199e148eb290

<img width="865" alt="Screen Shot 2022-06-26 at 2 52 16 PM" src="https://user-images.githubusercontent.com/33462905/175801475-99f826db-7343-4c4e-8064-0561a5252e39.png">

**Comment by nijamaDev** [comment]
I have discovered many ways in which collections are kinda broken. The 2 most noticeable are:
---
##  1. Board, Group by: Status
When something is grouped by a Status property, the board view is **completly broken / Won't render the page at all**
###  Notion page (Origin):
![image](https://user-images.githubusercontent.com/37962012/204320425-7cb4e6a9-bc04-4be7-8c8c-58a7a2436943.png)
### The resulting page will cause a build error when trying to render it. WON'T render
![image](https://user-images.githubusercontent.com/37962012/204317470-f66c2f74-ea5a-4136-a610-5c4a5dc89064.png)

## 2. Table views side by side
when there are 2 table views side by side in a _"2 column block"_ the render output will be messed up.
### Notion page (Origin):
![image](https://user-images.githubusercontent.com/37962012/204319455-ea22db81-d993-4b7b-8ada-b87720741649.png)
### Render output:
![image](https://user-images.githubusercontent.com/37962012/204319372-c3df874a-d295-4b3c-b721-1df2332aa40c.png)
Note that in the output there are no scrollbars and is completly static (no horizontal scrollable)

**Comment by alisolanki** [comment]
I'm still facing the same issue when I try to render it on mobile ([example](https://www.alisolanki.com/projects-and-builds)), is there a solution to this?

**Comment by transitive-bullshit** [comment]
Closing as I believe this is fixed in the latest update.
