### ISSUE TITLE
Embedded gif not working

### ISSUE THREAD

**Issue by Vadorequest** [NotionX/react-notion-x#263]
Integrating this gif in Notion `https://tenor.com/view/birthday-happy-birthday-balloon-hbd-steve-harvey-gif-22808994` works well on Notion but doesn't display well on the website.

On Notion (iframe element):
![image](https://user-images.githubusercontent.com/3807458/162593732-f7b22f44-1abd-422a-afc5-d717520ef2d6.png)

On website (video element):
![image](https://user-images.githubusercontent.com/3807458/162593739-3b673cbf-d49f-464e-a4a5-1dce54f14131.png)

I can't really share the Notion page because it's writable for everybody, but adding the above URL in any Notion page will be enough to troubleshoot the issue.

I guess the site should use an iframe element, too. (but not sure what that change could break)

---
Reported at https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/264

**Comment by s4nju** [comment]
How are you embedding it? As far as I can see, this is working fine for me. pageId - `c97309777c36485c9bc620d02d89d8d5` 

Can you please explain how to reproduce?

**Comment by transitive-bullshit** [comment]
Closing as no repro.
