### ISSUE TITLE
401 Error on accessing the private notion page using Auth token.

### ISSUE THREAD

**Issue by yogeshwaran-ramesh** [NotionX/react-notion-x#267]
#### Description
401 Error on accessing the private notion page using Auth token.
`export const notion = new NotionAPI( {authToken: notionToken});`
im using the above code as mentioned in react-notion-x.
Please help me with this issue.

**Comment by transitive-bullshit** [comment]
This may help you: https://github.com/NotionX/react-notion-x/pull/248#issuecomment-1086959634

**Comment by ggiande** [comment]
#248 points to #256, which is now merged. I am unsure if notion-compat client or newer has been adopted across all examples. I am attempting to use the NextJS minimal example and it does not use the new useOfficialNotionAPI client that's in the full version. Any advice on how to proceed?

**Comment by transitive-bullshit** [comment]
I currently do not recommend using `notion-compat` if you want to faithfully render notion content. There are just too many blocks where notion doesn't expose enough formatting data for us to render content as you would expect. See https://github.com/NotionX/react-notion-x/pull/256 for more info.

I definitely agree that our docs could be improved here.

I'd love to add sections to the readme on "How to access private pages" and "How to use with the official Notion API". But my time is constrained, and this is an unpaid side project for me, so things aren't perfect.

**Comment by ggiande** [comment]
> 

Can I work on a PR to add verbatim what I wrote above in the README.md?

**Comment by transitive-bullshit** [comment]
@ggiande PRs are always more than welcome :)
