### ISSUE TITLE
Bug: Module not found: Can't resolve 'mem'

### ISSUE THREAD

**Issue by vutoan266** [NotionX/react-notion-x#299]
Hi,
I have encountered the issue after installing `react-notion-x` and importing it into my project like the image below.

![image](https://user-images.githubusercontent.com/18349710/171391893-0a8df906-8cdb-4460-ba83-d7808369d083.png)

Not sure why it happens but I tried to install `mem` package or downgrade version of `react-nation-x` but it still doesn't work.
Please help me. Thank you in advance.

**Comment by transitive-bullshit** [comment]
Hey @vutoan266, just to help me debug what might be going on for you, what version of Node.js are you using and which package manager + version?

**Comment by transitive-bullshit** [comment]
Is your project open source? I'm not currently able to reproduce the issue.

Does the problem repro if you use `yarn` instead of `npm`? I'm not saying you should use yarn; I'm just trying to diagnose what might be going on.

**Comment by vutoan266** [comment]
Hi, after try to delete package-lock and yarn lock files and then re-install, but it did not work too. 

Sorry, my project is not open source. Here are some config of the project:
![image](https://user-images.githubusercontent.com/18349710/171544997-58165cb5-9384-4381-9c36-86dac097808f.png)
![image](https://user-images.githubusercontent.com/18349710/171545019-56a555df-df8b-4f45-8dff-5623f30999ba.png)

And here is the error message in Console browser:
![image](https://user-images.githubusercontent.com/18349710/171544792-c4a0f078-6544-4d25-b600-48f28829c028.png)

Hope it is useful for you to think about the potential issue orz.

**Comment by vutoan266** [comment]
Hey @transitive-bullshit , this bug has been resolved. It happened due to my project uses craco with react-script v4. I just upgrade to v5, and it works well with `react-notion-x`. Thank you a lot for your help. Can close this issue.

**Comment by transitive-bullshit** [comment]
imho, `create-react-app` is unfortunately very poorly maintained at this point. In the future, I would recommend looking into [other options](https://transitivebullsh.it/javascript-dev-tools-in-2022#f2dc15819a65412a978bcfdb5c2ae13e) if possible.
