### ISSUE TITLE
Styles for columns aren't the same on Safari

### ISSUE THREAD

**Issue by normdoow** [NotionX/react-notion-x#30]
I noticed that styles for columns aren't looking the same on safari as they are on chrome. I think styes should look more like the chrome version. Here are screenshots from both on the https://react-notion-x-demo.transitivebullsh.it website.

On Chrome:
![image](https://user-images.githubusercontent.com/21371266/107890701-22704200-6ecf-11eb-8d7f-6fcefcdb1e9f.png)

On Safari
![image](https://user-images.githubusercontent.com/21371266/107890656-ee951c80-6ece-11eb-9c44-a039302bb31b.png)

I'd be glad to take a stab at fixing this if you'd like when I have time in a couple of days.

**Comment by transitive-bullshit** [comment]
Definitely a bug; if anyone gets to investigating this before me, start from https://github.com/NotionX/react-notion-x/blob/master/packages/react-notion-x/src/block.tsx#L580

**Comment by normdoow** [comment]
Fixed by https://github.com/NotionX/react-notion-x/pull/37

**Comment by transitive-bullshit** [comment]
@normdoow small tip: if you put "Fixes #30" in your PR comment, then this issue will automatically be closed once the PR is merged. But it doesn't work the other way around 😉

**Comment by transitive-bullshit** [comment]
Should be fixed by `react-notion-x@4.3.1`

**Comment by normdoow** [comment]
> @normdoow small tip: if you put "Fixes #30" in your PR comment, then this issue will automatically be closed once the PR is merged. But it doesn't work the other way around 😉

Ahh thanks! Didn't know that.
