### ISSUE TITLE
Would it be possible to allow clickable images?

### ISSUE THREAD

**Issue by vader1359** [NotionX/react-notion-x#306]
I know that Notion does not have this option. But as react-notion-x can replace the original image with `next/image`, is it possible to wrap the image with a hyperlink (for example, based on the caption)?

**Comment by vader1359** [comment]
I just realized that this feature has already existed.

**Comment by transitive-bullshit** [comment]
You can set a URL as the image's caption, and instead of showing the caption as it does in Notion, the resulting image will be clickable to open a new tab in the caption's URL.
