### ISSUE TITLE
Does `getCollectionData` work with filter?

### ISSUE THREAD

**Issue by bytrangle** [NotionX/react-notion-x#324]
#### Description

Not familiar with the what goes behind [getCollectionData](https://github.com/NotionX/react-notion-x/blob/master/packages/notion-client/src/notion-api.ts#L309) but it seems like the filter feature hasn't been included yet?

Filter is one feature which seems to undergo quite a change recently in Notion, so do you have a plan to work on it for the unofficial API?

#### Notion Test Page ID

cc368b47772a4a1aa36e1f52c507d20d

**Comment by normdoow** [comment]
This should now be supported in https://github.com/NotionX/react-notion-x/pull/333
