### ISSUE TITLE
Error when using getAllPagesInSpace

### ISSUE THREAD

**Issue by gmpetrov** [NotionX/react-notion-x#327]
#### Description

Hello 

I get this error when calling getAllPagesInSpace (from notion-utils)

page load error { pageId: 'd87f740a-3e6b-4c82-8665-9ec50c9ab16a', spaceId: undefined } undefined Cannot read properties of undefined (reading 'getPageRaw')

`
    import { getAllPagesInSpace } from 'notion-utils';
    import { NotionAPI } from 'notion-client';

    const notion = new NotionAPI();

    const pages = await getAllPagesInSpace(
      "d87f740a-3e6b-4c82-8665-9ec50c9ab16a",
      undefined,
      notion.getPage,
      {
        traverseCollections: false,
      }
    );
`

"notion-client": "^6.12.9"
"notion-types": "^6.12.6"
"notion-utils": "^6.12.9"
"react-notion-x": "^6.12.10",

Is it a bug or am I doing something wrong?

#### Notion Test Page ID

Public page

https://gpetrov.notion.site/Product-Wiki-d87f740a3e6b4c8286659ec50c9ab16a

**Comment by gmpetrov** [comment]
I made it work. It might be caused by having multiple instances of NotionAPI client in the same app.

**Comment by thebasedbob** [comment]
Do you remember if there was anything in specific you changed to fix this? 

I'm having the same error occur and not sure what is causing this. I don't believe I have multiple instances of NotionAPI client
