### ISSUE TITLE
New board view with status grouping property doesn't work

### ISSUE THREAD

**Issue by remorses** [NotionX/react-notion-x#329]
#### Description

When you create a new board Notion will send a new grouping data structure based on status

#### Notion Test Page ID
https://brave-iberis-6ea.notion.site/new-board-database-ea67139fc51e456db3a4e22c1da2e88e

https://react-notion-x-demo.transitivebullsh.it/ea67139fc51e456db3a4e22c1da2e88e

**Comment by normdoow** [comment]
Working on this.

**Comment by remorses** [comment]
I also found out that if you remove the status property and use another property for "grouping" the board works again with current code

**Comment by normdoow** [comment]
> 

yeah, currently boards only work with grouped by "select" type. Notion changed it  that you can group by about anything. So the fix  is pulling the  type that is used.

**Comment by normdoow** [comment]
PR here: https://github.com/NotionX/react-notion-x/pull/360
