### ISSUE TITLE
NotionAPI getSignedfileUrls error HTTPError: Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by AakashMallik** [NotionX/react-notion-x#331]
#### Description
All the static builds were fine up until 22nd July 2022, but since yesterday, I have started getting these errors in my build, and oddly, my development builds have become super slow.

This is the log I get while building both static production and SSR development builds.
```
NotionAPI getSignedfileUrls error HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/home/runner/work/pipe-runner-website/pipe-runner-website/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) ***
  code: undefined,
  timings: ***
    start: 1658648256775,
    socket: 1658648256776,
    lookup: 1658648256785,
    connect: 1658648256794,
    secureConnect: 1658648256804,
    upload: 1658648256804,
    response: 1658648256918,
    end: 1658648256918,
    error: undefined,
    abort: undefined,
    phases: ***
      wait: 1,
      dns: 9,
      tcp: 9,
      tls: 10,
      request: 0,
      firstByte: 114,
      download: 0,
      total: 1[43](https://github.com/Pipe-Runner-Lab/pipe-runner-website/runs/7486332222?check_suite_focus=true#step:7:44)
    ***
  ***
***
```

#### Notion Test Page ID

As far as I can tell, this is not a page-specific issue since earlier, the same pages have been working fine for me.
Also, I have done a shallow check and it seems the pages are rendered all right, but I am not sure yet.

#### Version

"notion-client": "5.0.0",
"notion-types": "5.0.0",
"notion-utils": "5.0.0",
"react-notion-x": "5.0.0"

Has something changed from Notion again?? 😢

**Comment by AakashMallik** [comment]
Bumping up the package version to `6.12.11` did not help. This seems like something that will break a lot of builds. Am I the only one facing this issue?

**Comment by ambyas** [comment]
Samething for US. The build process is broken

"notion-client": "^4.9.9",
"react-notion-x": "^4.11.3"

**Comment by remorses** [comment]
I think i found the problem, i am gonna open a PR soon

Basically i found that if you pass links that cannot be signed by Notion now it will give an error (the error happens only when you have other non video embeds in the page)

@AakashMallik Can you give me the Notion page url where you have the problem?

**Comment by AakashMallik** [comment]
@remorses I belive this is one page which was throwing this error: 
https://piperunner.notion.site/Keeping-your-code-clean-Linting-in-detail-ea06ce0b641d48299e193d811f68839f

The error itself is not really breaking anything in the rendered page, but the dev process becomes extremely slow since the page build waits for the error for some reason, in which case for a page that used to take 2-5sec to SSR now takes 2mins in dev.

**Comment by adlpz** [comment]
Can confirm that @remorses's PR seems to solve the issue for my project.

No idea if there may be additional edge cases tho.

**Comment by AakashMallik** [comment]
Thanks a lot, this solved the issue.
