### ISSUE TITLE
h1, h2, h3 blocks are rendered as h2, h3, h4

### ISSUE THREAD

**Issue by MartinXPN** [NotionX/react-notion-x#337]
#### Description
It seems like the blocks are rendered differently than expected. This appears when I render a page:
```html
<h4 class="notion-h notion-h3 notion-h-indent-0 ...></h4>
```

Also, text blocks appear as:
```html
<div class="notion-text notion-block-...></div>
```
I think, it would be great for SEO and other purposes to render the notion pages with the right blocks (h1 with h1, h2 with h2, and h3 with h3). For text blocks, wouldn't it be better to render them with `<p>...</p>`?

**Comment by pbteja1998** [comment]
I think this is intentional.

The main page title will anyways be h1, and it's recommended to only have one H1 in the page.

So, it makes sense to use these mappings.

Notion -> HTML
Heading1 -> h2
Heading2 -> h3
Heading3 -> h4

If we don't do this, Heading1 block in Notion will get wasted as no one would use it. Because there needs to be only one H1 and the page main title is already h1.


But I agree with the other suggestion. It would be better to have p instead of div for text blocks.

**Comment by MartinXPN** [comment]
Yeah, it makes sense for the page title. Unfortunately, I never render the whole page - only the contents. And in that use case the page doesn't have any h1 tags.

I think it would be more clear to have h1 corresponding to h1, h2 to h2, etc. Otherwise, it's both hacky and doesn't satisfy a concrete use case (which I think a lot of people have in their applications - I don't think everyone renders the whole page always).

**Comment by pbteja1998** [comment]
If you don't render the whole page, then you can manually add h1 yourselves, right?

There should be only one H1. So even if it behaves like you said, you would be using Heading1 block only once and you can only go 2 more levels Nested (meaning there is no way to add h4s from Notion in your case)

**Comment by MartinXPN** [comment]
For the first part, do you suggest extracting the notion h1 and rendering it manually as h1? If that's the case, I'd prefer to globally remap the heading and paragraph tags and not worry about this (not sure if that's possible). Please note I don't use the Notion title at all (it's used for a completely different purpose in my case).

Didn't quite understand the second part, sorry.

**Comment by pbteja1998** [comment]
https://github.com/NotionX/react-notion-x/blob/master/packages/notion-utils/src/get-page-title.ts

**Comment by MartinXPN** [comment]
Thanks a lot @pbteja1998 
I guess it would make sense to close this issue and maybe open another one only for `<p>` tags.
