### ISSUE TITLE
 notion client: export types

### ISSUE THREAD

**Issue by trindadematheus** [NotionX/react-notion-x#38]
export types to improve usability in typescript

![image](https://user-images.githubusercontent.com/31348285/109817655-ec41fa80-7c10-11eb-9778-2c53820ba5d2.png)

**Comment by transitive-bullshit** [comment]
@trindadematheus you're looking for the `notion-types` package which exports all types used by `react-notion-x`, `react-utils`, and `react-client`.

**Comment by trindadematheus** [comment]
`notion-types` helped me, thanks
