### ISSUE TITLE
Cannot build within Vercel/next project

### ISSUE THREAD

**Issue by dvdsgl** [NotionX/react-notion-x#41]
Sorry for the newb question, but after adding `notion-client` to my Vercel/next project, I get these errors:

```
info  - Creating an optimized production build  
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'tls' in '.../node_modules/resolve-alpn'
```

So I did the following as the same type of error kept arising:

```
$ npm install tls net http2 dns dgram
```

Finally, I am stuck here:

```
info  - Creating an optimized production build  
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'dgram' in '.../node_modules/native-dns-cache'
```

Can you please help me understand what I'm missing? Thank you!

### Environment

* `node v14.16.0`

**Comment by dvdsgl** [comment]
Closing for now—I can get a simple case to work, this must be due to some complexity somewhere outside of `react-notion-x` control.

**Comment by transitive-bullshit** [comment]
@dvdsgl this may have to do with `notion-client` relying on `got`. These types of errors come up in `got` from time to time..

**Comment by bytrangle** [comment]
@transitive-bullshit I'm not sure if I should open a new issue, but I also encounter the same error, but it is for the `dns` module. It seems to stem from `notion-cient` using `got`. I don't think I should install `dns` because it's a core module of Node.js already.
