### ISSUE TITLE
Hydration issue on Next.js 13

### ISSUE THREAD

**Issue by jamesvclements** [NotionX/react-notion-x#410]
#### Description

Seems like certain Notion blocks are causing a hydration issue, ~~but I can't (yet) tell which one(s)~~. Update: it seems to be the Code block and Collection blocks. I have a page that renders fine, but I'm trying to use [Super's Template Starter](https://docs.super.so/template-starter-kit/template-starter) page, and that has issues.

![Create Next App-Wednesday-November-23-2022-04 44 21PM](https://user-images.githubusercontent.com/20052710/203651494-9f1fec28-cb74-4bcd-8217-521fabe9a310.gif)

I removed all the components that were unsupported and added the third-party components but even without any warnings from the library the hydration issue is still there.

[Page without issues](https://witholdfriends.notion.site/Use-Your-Burn-Rate-292faa7c02c04a489e99cc875655a612)
[Page w/ issues](https://witholdfriends.notion.site/Template-Starter-37752ffcfc2b412780d20ddbe161356b)

Renderer Code:
```tsx
'use client';

import { ComponentPropsWithoutRef } from 'react';
import { NotionRenderer } from 'react-notion-x';
import { Collection } from 'react-notion-x/build/third-party/collection';
import { Code } from 'react-notion-x/build/third-party/code';
import { Equation } from 'react-notion-x/build/third-party/equation';
import TweetEmbed from 'react-tweet-embed';
import Image from 'next/image';
import Link from 'next/link';

export default function NotionRendererDefault(
    props: ComponentPropsWithoutRef<typeof NotionRenderer>
) {
    return (
        <NotionRenderer
            {...props}
            components={{
                Collection,
                nextImage: Image,
                nextLink: Link,
                ...props.components,
            }}
        />
    );
}

const Tweet = ({ id }: { id: string }) => {
    return <TweetEmbed tweetId={id} />
  }

export function NotionRendererForPosts(
    props: ComponentPropsWithoutRef<typeof NotionRenderer>
) {
    return (
        <NotionRenderer
            {...props}
            components={{
                nextLink: Link,
                nextImage: Image,
                Collection: Collection,
                Code: Code,
                Equation: Equation,
                Tweet: Tweet,
            }}
        />
    );
}

```

**Comment by jamesvclements** [comment]
Looks like the issue is with `notion-code`:
![Create Next App-Wednesday-November-23-2022-04 55 42PM@2x](https://user-images.githubusercontent.com/20052710/203652681-8e2a24b4-7bdd-4ae8-ab07-be5e7cc55592.png)

**Comment by jamesvclements** [comment]
Found this [similar issue ](https://github.com/NotionX/react-notion-x/issues/62)

**Comment by jamesvclements** [comment]
Removing the code block, there's another hydration issue regarding `style` in the collection block:
![Create Next App-Wednesday-November-23-2022-04 59 39PM@2x](https://user-images.githubusercontent.com/20052710/203653227-63f7a2fe-e254-48c6-a0b0-910938c2d193.png)

**Comment by jamesvclements** [comment]
Update — removing the Code Block and Collection Blocks stops the hydration errors

**Comment by transitive-bullshit** [comment]
Not sure if you're using it, but I don't think `next/dynamic` works with `appDir`.

In general, `appDir` is really pre-alpha at the moment imho, and I would recommend staying away from it.

I was also running into random React hydration errors working on an unrelated demo app: https://github.com/vercel/next.js/issues/43159

**Comment by FranciscoMoretti** [comment]
I'm also hitting this error with Collection Blocks displaying a list. I'm not using the `appDir`.

**Comment by kjs104901** [comment]
![image](https://user-images.githubusercontent.com/37609477/211197404-47cc18e0-f86a-4e50-b513-bc4f53dbb0dc.png)
![image](https://user-images.githubusercontent.com/37609477/211197424-3fd69baa-83b7-476d-b080-e0b62760cd18.png)
 
In my case, 
rendering a page that is written in a single table(Collection) and its icon
causes the problem.

The message disappears when I do
* Remove the icon of table
* Turn off the fullPage option
* Not render Collection (rendering result is a empty page)

**Comment by stimw** [comment]
> Looks like the issue is with `notion-code`: ![Create Next App-Wednesday-November-23-2022-04 55 42PM@2x](https://user-images.githubusercontent.com/20052710/203652681-8e2a24b4-7bdd-4ae8-ab07-be5e7cc55592.png)

same issue in Next.js 13

**Comment by 6unpk** [comment]
I think it appears on next.js 13 version. when i downgraded to next.js 12, it works.

**Comment by transitive-bullshit** [comment]
Try upgrading to latest release v7 which uses Next.js 15.
