### ISSUE TITLE
How to get all blog in notion

### ISSUE THREAD

**Issue by minnyww** [NotionX/react-notion-x#42]
in react-notion, i used api /table to get all blogs in my notion. 
but in react-notion-x, how to get all blogs in my notiob using table templates

**Comment by iuzn** [comment]
I thought about that too. I couldn't find a solution. I use react-notion and react-notion-x together in my project. I'm pulling the page-id with react-notion. Then I'm using react-notion-x to render the page. This is my instant solution. I'm trying to create different components with Notion. So I need to get direct access to json data. This is a problem I have been thinking about for a long time. If my project grows in the future, I will need to allocate a budget for api-worker.

Sample page in my blog project: [[pageSlug].tsx](https://github.com/iuzn/developer-blog/blob/master/pages/%5BpageSlug%5D.tsx)

**Comment by transitive-bullshit** [comment]
With `react-notion-x`, you just need to do `getPage`. The result will have any and all table data built into the response.

For example, if you go to my website https://transitivebullsh.it, open up the developer console, and then type `recordMap`, you'll the result from `getPage` which contains all of the `collection`, `collection_query`, and `collection_data` that contain everything you need to render the collections (tables / gallery / lists / kanban / etc).

**Comment by transitive-bullshit** [comment]
@luzn `notion-client` gives you direct access to the JSON returned from Notion's API. There isn't any data or use case where `react-notion` provides data that isn't handled by `notion-client` and `react-notion-x`.

**Comment by iuzn** [comment]
`notion-client` is great. Thank @transitive-bullshit for your effort. I guess I will no longer receive promotional emails from Cloudflare. I continue with only Vercel.
