### ISSUE TITLE
Nextjs: `nextImage: Image` has no effect

### ISSUE THREAD

**Issue by bmitchinson** [NotionX/react-notion-x#447]
#### Description

I'm overriding the "nextImage" components attribute, but no images are replaced by the `next/image` component.
I've tried looking through the "full" example pretty extensively, but can't understand why my override isn't taking effect. I believe I'm following the steps properly from the readme.

I should be able to use nextImage without worrying about image previews right? Since that's not mentioned in the readme example? Using `<Image />` directly on the page works to utilize the `/next/` image, as seen in my author icon on my blog post.

- [link to my notionrenderer](https://github.com/bmitchinson/nobelium-mitchinson-dev/blob/ac6e405bea8ac08df008d332a0ac7ad07009bb18/layouts/layout.js#L80)
- [link to my blog post image not using next (see src isn't `/next/...`)](https://blog.mitchinson.dev/Class-Fall19)

#### Ideas

[I have the domains in `next.config.js` set like they are in the full example, but that hasn't made a difference.](https://github.com/bmitchinson/nobelium-mitchinson-dev/blob/13c48f207269751998f64549b848a510380a90ad/next.config.js#L8)

#### Notion Test Page ID

https://bmitchinson.notion.site/Classes-Fall-2019-79a7ea081b4445e6ba45a342a8c4bb13

#### Notes
```tsx
<NotionRenderer
              recordMap={blockMap}
              // previewImages={true}
              // https://github.com/NotionX/react-notion-x/blob/2a48b29554b4ecf3cf49db808c8660726717e255/examples/full/components/NotionPage.tsx#L166
              components={{
                Code,
                Collection,
                nextLink: Link,
                nextImage: Image,
              }}
              mapPageUrl={mapPageUrl}
            />
```

<img width="500" alt="image" src="https://user-images.githubusercontent.com/33632286/222978597-66358a2c-2784-474c-99d5-69ca278e510c.png">

**Comment by transitive-bullshit** [comment]
My guess is that this may be due to using Next.js 13+, whereas this project and it's accompanying [boilerplate](https://github.com/transitive-bullshit/nextjs-notion-starter-kit) are still using Next.js 12. There were quite a few changes with `next/image` with Next.js 13, and that may be the difference.

In general, the next/image interop code is more brittle than I'd like, but it used to work with Next.js 12.

@normdoow have you upgraded to Next.js 13 or do you have any ideas on this?

**Comment by bmitchinson** [comment]
I should have included that in my initial comment but, I'm using next `^12.3.2`.

I tried to use the same nextjs version as what's used in the "full" example, and that didn't make a difference either.

**Comment by bmitchinson** [comment]
It looks like the full example is potentially not utilizing nextLink as well #427

**Comment by bmitchinson** [comment]
Fixed this issue by correctly using image previews.
[Example: My code](https://github.com/bmitchinson/blog.mitchinson.dev/commit/71f4773fad3737c2ae0c8fdff12e508794722e5e)

[Example: react-notion-x/examples/full](https://github.com/NotionX/react-notion-x/blob/v6.16.0/examples/full/components/NotionPage.tsx#L154)

The trick was [enabling preview images](https://github.com/NotionX/react-notion-x/blob/2a48b29554b4ecf3cf49db808c8660726717e255/examples/full/components/NotionPage.tsx#L166)

[Why preview images need to be enabled](https://github.com/NotionX/react-notion-x/blob/2a48b29554b4ecf3cf49db808c8660726717e255/packages/react-notion-x/src/components/lazy-image.tsx#L143)

[Note about cost](https://github.com/NotionX/react-notion-x/blob/2a48b29554b4ecf3cf49db808c8660726717e255/examples/full/lib/config.ts#L8)

[Another note about cost](https://github.com/NotionX/react-notion-x/commit/6493adc87a8f2dbb6b3881e27325a19501024789) (transitive-bullshit disabling it because it was costing them 1000s)

**Comment by luckyBricks** [comment]
@bmitchinson Really appreciate your code sample, I'm seeking a similar way by repacing the <img> with next/image component. So that I can add an image proxy in the global next.config.js. 

I spend almost one day to find a way to implement it and finally I got here.
