### ISSUE TITLE
want to know if this project supports rendering comments,or have some alternative?

### ISSUE THREAD

**Issue by est7** [NotionX/react-notion-x#451]
#### Description

This is an amazing project. I want to know if this project supports rendering comments, just like the image below. On the right side of the page, I hope to display my comments on the article and link them to the marked content.

![image](https://user-images.githubusercontent.com/17064360/224607356-c0a87a85-885d-4407-b0ed-6171b8e63bfd.png)

#### Notion Test Page ID

https://1est.notion.site/How-to-use-search-engine-optimization-to-drive-sales-381bf16cb7f04ad79d6d20d5915b2185

**Comment by est7** [comment]
I often use web clipper and mark articles, so I want to have this feature so that I can directly see the content of my comments in my static blog in the future

**Comment by KIMSEUNGGYU** [comment]
I want it too

**Comment by venkr** [comment]
It looks doable:
- text chunks can have a decoration "m", with a discussion-id. [It's currently ignored](https://github.com/NotionX/react-notion-x/blob/e1f03de6100f2cd33c146eb1c5e67ec4d4afe522/packages/react-notion-x/src/components/text.tsx#L145).
- The top-level `recordMap`, contains `discussion` and `comment`. The comments have the discussion as a parent-id.

I think _finding_ them is easy, but figuring out a DOM + styling solution that you can transform into easily is a bit harder. (Especially with the responsiveness Notion provides).

Perhaps the easiest solution would be to add them as footnotes at the bottom of your document or so.

**Comment by transitive-bullshit** [comment]
No comments support currently; not planned unless there's a high quality PR which adds it as optional. I wouldn't want them displayed by default, so possibly an additional `displayComments: true` property to `NotionRenderer`.
