### ISSUE TITLE
Why am I getting this error, "Attempted import error: 'useRef' is not exported from 'react' (imported as 'React5')."

### ISSUE THREAD

**Issue by Geuni620** [NotionX/react-notion-x#466]
#### Description

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/56650238/231386338-38382e73-d481-491d-8454-6c0bedaa786c.png">

![image](https://user-images.githubusercontent.com/56650238/231387620-df45edf6-4cb6-465f-911d-3524bca32458.png)

#### Notion Test Page ID

---

Hi there.

Recently, I'm trying to create a blog using Notion.

I want to use react-notion-x, the app directory next.js.

- node version: 18.15.0
- next.js: 13.3.0

1. Does next.js not support 'app directory'?
2. if not, is it possible to use react-notion-x in the pages folder to use only the part related to notion and the rest in the app folder?
3. If you have another way to do it, or I'm missing something, please let me know.

Thank you in advance. 🙇‍♂️

**Comment by Geuni620** [comment]
It turns out it was just because I didn't include 'use client'. 🥲

**Comment by 0xPT** [comment]
How did you get this to work? Using "use client" throws `Module not found: Can't resolve 'dns'` and not using "use client"
throws the error you received.. Using Next 13.4.1

**Comment by 0xPT** [comment]
@Geuni620 my friend I appreciate the time you took to reply to me. Your recommendation resolved my problem.

Thanks so much!

**Comment by vader1359** [comment]
@Geuni620 
Hello, do you some how get the next/image or next-cloudinary supported in the new AppRouter?
The components attribute in `NotionRenderer` works well in PageRouter but it fetch the raw data link in the new AppRouter.
