### ISSUE TITLE
Error: Notion page not found "xxxxxxxx"

### ISSUE THREAD

**Issue by ivalsaraj** [NotionX/react-notion-x#47]
# Problem
The Notion page is not loading, showing `Error: Notion page not found "b23d2d383bbe49a0bb983837cc486862"`

# Reproduce
Create a notion page in personal free account and `https://www.notion.so/Testtt-b23d2d383bbe49a0bb983837cc486862` copy the page id from the page url and pass to `await notion.getPage('b23d2d383bbe49a0bb983837cc486862')` it gives `Error: Notion page not found "b23d2d383bbe49a0bb983837cc486862"`

# Expected Behaviour
It should show the page and this was working before and not sure which recent update caused this issue.

Thanks in advance

**Comment by ivalsaraj** [comment]
Resolved by updating to latest version

**Comment by transitive-bullshit** [comment]
@ivalsaraj these are the best types of issues 😄

**Comment by airtonix** [comment]
updated to latest and still getting this error.
