### ISSUE TITLE
Tweet embeds not working 

### ISSUE THREAD

**Issue by Utkarshbhimte** [NotionX/react-notion-x#48]
Hey maintainers.

There is a bug on tweet embeds
![image](https://user-images.githubusercontent.com/13379773/112726540-fcb17080-8f43-11eb-928d-6909e34308ef.png)

I am currently implementing this on a NextJS project

react-notion-x version: 4.3.7

What needs to be done here?

**Comment by transitive-bullshit** [comment]
Larger third-party blocks like `tweet`, `pdf`, etc are all opt-in.

For an example of how to enable these larger components, check out https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/components/NotionPage.tsx#L252, https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/components/NotionPage.tsx#L164, and https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/components/NotionPage.tsx#L12

**Comment by Utkarshbhimte** [comment]
Thanks for your fast response. 👍
