### ISSUE TITLE
Create React App

### ISSUE THREAD

**Issue by leopolicastro** [NotionX/react-notion-x#5]
My apologies if this is a stupid question, I'm trying to add `react-notion-x` into my `create-react-app` and I keep getting the following error when I follow your example:

```text
./node_modules/react-notion-x/build/esm/block.js
Module not found: Can't resolve 'next/dynamic' in '/Users/.../node_modules/react-notion-x/build/esm'

```
What am I doing wrong? Is this for Next.js applications only or can I use it with `create-react-app`?

**Comment by transitive-bullshit** [comment]
This is a great question.

Right now, we rely on Next.js's `next/dynamic` for lazy-loading some of the larger dependencies so CRA and other bundlers aren't supported.

This definitely isn't an ideal solution, but I'm not sure the best way to solve this issue in a way that works across different bundlers.

I'm very open to ideas; in the meantime, hopefully [react-notion](https://github.com/splitbee/react-notion) will work for you.

**Comment by leopolicastro** [comment]
Thanks for getting back to me. I was able to get react-notion working but only for one page and not any of the subpages in the workspace. I'll keep tinkering with it and see if I can get it to load all the subpages as well.

**Comment by transitive-bullshit** [comment]
Just a head's up that `react-notion-x` now supports CRA and any other React framework. 💪
