### ISSUE TITLE
Webpack 5 Adoption

### ISSUE THREAD

**Issue by iuzn** [NotionX/react-notion-x#51]
#### I want to use the 3x Faster Refresh feature that comes with Next.js 10.1, but I'm getting an error from react-notion-x. 
Source: [Webpack 5 Adoption
](https://nextjs.org/docs/messages/webpack5)

I get errors when I add this code block to `next.config.js` file:
```js
module.exports = {
  future: {
    webpack5: true,
  },
}
```
Error Message:
```js
./node_modules/react-notion-x/build/esm/index.js
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export * from './types';
| export * from './utils';
| export * from './context';
```

Obviously, I don't know the webpack side, I'm not sure the problem is with my configurations. I'd appreciate it if you'd help me.

_Thanks._

**Comment by transitive-bullshit** [comment]
Thanks @iuzn.

Just added webpack 5 support in `4.4.0`.

Please let me know if you run into any issues.

**Comment by transitive-bullshit** [comment]
Hmmm, it seems that some of the issues were resolved with this change, but I haven't been able to get webpack 5 working with https://github.com/transitive-bullshit/nextjs-notion-starter-kit yet.

I've been banging my head against this for a few hours now; see https://github.com/vercel/swr/issues/1112.

**Comment by iuzn** [comment]
Any error don't appear with `4.5.0`
Thanks @transitive-bullshit for hard effort.
