### ISSUE TITLE
Question about getting a page's raw HTML for RSS feeds

### ISSUE THREAD

**Issue by spencerwooo** [NotionX/react-notion-x#53]
Is there a way to get the raw HTML for a notion page? So that we could build an content-included RSS feed of, say, a blog post, instead of only having the title and url link at our hands.

**Comment by iuzn** [comment]
You look this [nobelium/lib/rss.js](https://github.com/craigary/nobelium/blob/main/lib/rss.js)

**Comment by normdoow** [comment]
I believe the html wouldn't be needed for an RSS feed. The feed would all be based on your sites page links and page descriptions. react-notion-x shouldn't be have anything to do with these steps even though you may be using it to render out your pages. RSS feed example: https://www.w3schools.com/XML/xml_rss.asp

**Comment by spencerwooo** [comment]
@normdoow 

> The feed would all be based on your sites page links and page descriptions.

Yes that's what I am doing currently. However I would also like to **include the whole article in the RSS feed** besides the link, title, and descriptions. Including the whole article means I need access the HTML output of my rendered Notion page, no?

**Comment by normdoow** [comment]
@spencerwooo, I don't think adding html to an RSS Feed would be normal. I don't see any fields here that would make me thing that you would do that: https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt
I think instead you would just want to link to your website page for each item.

**Comment by transitive-bullshit** [comment]
See https://reactjs.org/docs/react-dom-server.html
