### ISSUE TITLE
Some errors about dns?

### ISSUE THREAD

**Issue by wwei-github** [NotionX/react-notion-x#530]
#### Description

When I followed the instructions in the readme and used the code provided, I encountered some errors after finishing yarn and running the project.

<img width="1083" alt="image" src="https://github.com/NotionX/react-notion-x/assets/46670626/ba695047-386f-4c97-bd54-d7390040fbc1">

#### Notion Test Page ID
067dd719a912471ea9a3ac10710e7fdf

**Comment by svengau** [comment]
finally worked for me with `"got": "^12.6.1"`

**Comment by transitive-bullshit** [comment]
You may need to add:

```
"overrides": {
    "cacheable-request": {
      "keyv": "npm:@keyvhq/core@~1.6.6"
    }
  }
```

to your package.json

Though I believe the recently released v7 may remove the need for this.
