### ISSUE TITLE
Deploy the latest version on npm

### ISSUE THREAD

**Issue by hkirat** [NotionX/react-notion-x#537]
#### Description

Seems like the latest version (16.0.2) isn't yet deployed to npmjs. Would be great if it could be deployed there. 
Unsure if the workflow breaking on the latest commit is to blame here, but happy to dig in further

https://github.com/NotionX/react-notion-x/actions/runs/6395867834/job/17360465322

**Comment by transitive-bullshit** [comment]
Done; thanks!
