### ISSUE TITLE
Failed to resolve 'p-queue' from 'notion-utils'

### ISSUE THREAD

**Issue by hhmy27** [NotionX/react-notion-x#543]
Hi, I've encountered a problem. After running the following commands:

```bash
pnpm add react-notion-x
pnpm add notion-client
pnpm add notion-utils
pnpm add p-queue
```

My `package.json` dependencies are as below:

```json
"dependencies": {
  "notion-client": "^6.16.0",
  "notion-types": "^6.16.0",
  "notion-utils": "^6.16.0",
  "p-queue": "^8.0.1",
  "plasmo": "0.84.2",
  "react": "18.2.0",
  "react-dom": "18.2.0",
  "react-notion-x": "^6.16.0"
},
```

However, when I start the project, it prompts me with the following error:

```bash
🔴 ERROR  | Build failed. To debug, run plasmo dev --verbose.
🔴 ERROR  | Failed to resolve 'p-queue' from './node\_modules/.pnpm/notion-utils@6.16.0/node\_modules/notion-utils/build/index.js'
🔴 ERROR  | Cannot load file './index' from module 'p-queue'
```

I have tried many ways to install `p-queue`, but all attempts have failed. I've been stuck on this issue for two days. Could anyone help me figure out how to successfully install it?

**Comment by transitive-bullshit** [comment]
What is `plasmo`? You shouldn't have to add any additional dependencies like `p-queue`, since it's included as a dependency of `notion-utils` ([source](https://github.com/NotionX/react-notion-x/blob/master/packages/notion-utils/package.json#L35)).
