### ISSUE TITLE
`katex` Requires Update

### ISSUE THREAD

**Issue by powersagitar** [NotionX/react-notion-x#551]
#### Description

Package `katex` that [`packages/react-notion-x`](https://github.com/NotionX/react-notion-x/blob/e1f03de6100f2cd33c146eb1c5e67ec4d4afe522/packages/react-notion-x/package.json#L27) depends on has a few security vulnerabilities:
- https://github.com/advisories/GHSA-64fm-8hw2-v72w
- https://github.com/advisories/GHSA-f98w-7cxr-ff2h
- https://github.com/advisories/GHSA-3wc5-fcw2-2329
- https://github.com/advisories/GHSA-cvr6-37gx-v8wc

It is better to bump `katex` to `0.16.10` to install the patches. 

Currently `katex` is on [`0.15.3`](https://github.com/NotionX/react-notion-x/blob/e1f03de6100f2cd33c146eb1c5e67ec4d4afe522/packages/react-notion-x/package.json#L27).

**Comment by rossirpaulo** [comment]
Any progress?

**Comment by rossirpaulo** [comment]
How do we patch this manually?

**Comment by transitive-bullshit** [comment]
See latest update; thanks!
