### ISSUE TITLE
require() of ES Module error 

### ISSUE THREAD

**Issue by karishag** [NotionX/react-notion-x#553]
#### Description

On the server side, when using `notion-client` package I get the `require() of ES Module` not supported error. 
I modified tsconfig.json file compilerOptions to this:

> "target": "ES2018", /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', 'ES2021', or 'ESNEXT'. */
    "resolveJsonModule": true, /* Resolve 'import x from y.json' to 'y.json'. */
    "module": "CommonJS"

Also installed esm module, and set "type": "module" in package.json file but nothing helps.

#### Notion Test Page ID
067dd719-a912-471e-a9a3-ac10710e7fdf

<img width="1029" alt="Screenshot 2024-05-16 at 10 49 04 AM" src="https://github.com/NotionX/react-notion-x/assets/41419834/e0cd66ea-efab-475c-bdec-0fc8138a798b">

**Comment by runticle** [comment]
Hey @karishag did you find a fix for this in the end?

**Comment by karishag** [comment]
@runticle in my case the project was CommonJS, I experimented a lot to continue using the same project but didn't work. Ultimately I've to create a new one with esm

**Comment by transitive-bullshit** [comment]
This project will only support ESM. https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
