### ISSUE TITLE
Getting HTTPError: Response code 401 (Unauthorized) with notion-client

### ISSUE THREAD

**Issue by muke5hy** [NotionX/react-notion-x#554]
#### Description

I am constatnly getting following error, token and database ID works with `@notionhq/client` but it is not working with `notion-client` What am I doing wrong? 

⨯ Internal error: HTTPError: Response code 401 (Unauthorized)
    at Request.eval (./node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
digest: "1102196494"

#### Notion Test Page ID

NOTION_AUTH_TOKEN=secret_thisisasecreat
NOTION_DATABASE_ID=8a42e373328c49a9a495ddd05fce7fa3

**Comment by ywj3493** [comment]
I got exactly same issue.

**Comment by ywj3493** [comment]
> #### Description
> I am constatnly getting following error, token and database ID works with `@notionhq/client` but it is not working with `notion-client` What am I doing wrong?
> 
> ⨯ Internal error: HTTPError: Response code 401 (Unauthorized) at Request.eval (./node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) digest: "1102196494"
> 
> #### Notion Test Page ID
> NOTION_AUTH_TOKEN=secret_thisisasecreat NOTION_DATABASE_ID=8a42e373328c49a9a495ddd05fce7fa3

I have resolved my issue. In case you encounter a similar situation, please refer to this.

The NotionAPI class has a problem with the authToken option, but if you just need to retrieve some data, you don’t need to authorize.

```typscript
import { Client } from "@notionhq/client";
import { DatabaseObjectResponse } from "@notionhq/client/build/src/api-endpoints";
import { NotionAPI } from "notion-client";

const notionToken = process.env.NOTION_KEY;
const notionDatabaseId = process.env.NOTION_DATABASE_ID;

const notion = new Client({
  auth: notionToken,
});

const notionApi = new NotionAPI();

export async function getPosts() {
  const response = await notion.databases.query({
    database_id: notionDatabaseId as string,
    filter: {
      property: "상태",
      status: {
        equals: "공개",
      },
    },
  });

  return response.results as DatabaseObjectResponse[];
}

export async function getPage(id: string) {
  const response = await notionApi.getPage(id);

  return response;
}
```

**Comment by ywj3493** [comment]
![image](https://github.com/NotionX/react-notion-x/assets/37992140/ce3ff44d-e5fa-4f5b-8436-f7ecdfc51d39)

authToken for NotionAPI is not secret key. you need to check `token_v2` for chrome developer tool.

**Comment by muke5hy** [comment]
> ![image](https://private-user-images.githubusercontent.com/37992140/333489915-ce3ff44d-e5fa-4f5b-8436-f7ecdfc51d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2OTc0NzcsIm5iZiI6MTcxNjY5NzE3NywicGF0aCI6Ii8zNzk5MjE0MC8zMzM0ODk5MTUtY2UzZmY0NGQtZTVmYS00ZjViLTg0MzYtZjdlY2RmYzUxZDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA0MTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkODRhNGI4ZmMwMjg3Zjk1MzBlODc3OGQyYTYwMTY4OGI2OWNjZTc1ZmJjYmIwMDdmMWE4YWMwMDk1OWE4NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NlbVNsqKgZwHuMw8atldArNvuNDlnLoZqSPIW8MUhus)
> 
> authToken for NotionAPI is not secret key. you need to check `token_v2` for chrome developer tool.

Will this token_v2 ever changes, say when user logs out of Notion?

**Comment by takasay** [comment]
I am hesitant to rely on this cookie token thing personally.
I found another way via the Notion official API if you want to retrieve a private page.

https://github.com/NotionX/react-notion-x/tree/master/packages/notion-compat

```ts
import { Client } from '@notionhq/client'
import { NotionCompatAPI } from 'notion-compat'

const notion = new NotionCompatAPI(
  new Client({ auth: process.env.NOTION_TOKEN })
)

const recordMap = await notion.getPage(pageId)
```

Note that there are some compatibility limitations if you use `notion-compat`.

**Comment by transitive-bullshit** [comment]
I recommend using the official Notion API if you need private access with an auth token.

This lib is mainly meant to access public notion data.

**Comment by liaodalin19903** [comment]
@transitive-bullshit  If it only query the public page, I think this library doesn't make much sense,  beacuse users can load the page by webview directly.

**Comment by transitive-bullshit** [comment]
@liaodalin19903 this library has been around for a long time, before notion's public pages were good and before they ever had an api. you can still do a lot of customization that you can't do with the official public pages.
