### ISSUE TITLE
Handle notion callouts without icon

### ISSUE THREAD

**Issue by AramMolins** [NotionX/react-notion-x#565]
#### Description

Recently, Notion added the possibility to remove an icon from a callout. That looks great in Notion but in the static website it is yet not handled.
Notion look:
![imatge](https://github.com/user-attachments/assets/568cce06-810e-45a8-8ef7-3e1ea9714d6c)

Static website look:

![Screenshot 2024-10-07 at 20-18-29 ÒPTICA](https://github.com/user-attachments/assets/a0b79e5d-501c-4b5d-b811-fafd9831a806)
(don't mind the background color).

I can change the CSS, but when removing the icon from the callout, it also removes the icon from any page or other callout. So somehow there should be a CSS class for callouts that do not contain an icon.

**Comment by wustep** [comment]
submitted https://github.com/NotionX/react-notion-x/pull/586 :)

**Comment by transitive-bullshit** [comment]
Should be fixed thanks to @wustep in https://github.com/NotionX/react-notion-x/releases/tag/react-notion-x%407.2.4
