### ISSUE TITLE
Merging the ky-universal broke the builds. Should we bump ky and node versions?

### ISSUE THREAD

**Issue by onnimonni** [NotionX/react-notion-x#572]
@transitive-bullshit after merging the #394 the newly added `import 'ky-universal'` breaks builds: https://github.com/NotionX/react-notion-x/actions/runs/11605079223/job/32314865994#step:5:46

I guess it would be easier to try instead to use [ky 1.0.0](https://github.com/sindresorhus/ky/releases/tag/v1.0.0) where `ky-universal` is not needed anymore.

It would mean that we need to bump the minimum supported node version to >=18 which [supports native fetch](https://nodejs.org/docs/latest-v18.x/api/globals.html#fetch).

**Comment by transitive-bullshit** [comment]
Fixed by https://github.com/NotionX/react-notion-x/pull/571
