### ISSUE TITLE
v7 Changelog?

### ISSUE THREAD

**Issue by pnodet** [NotionX/react-notion-x#574]

**Comment by transitive-bullshit** [comment]
95% maintenance in https://github.com/NotionX/react-notion-x/pull/571

- updating all deps to latest
- enabling strict mode for typescript and fixing some resulting ts issues
- move from yarn + lerna + tsc to pnpm + turbo + tsup + changesets
- a dozen minor bug fixes from PRs

Overall, there shouldn't be any major breaking changes aside from dep updates and min node version >= 18.

**Comment by pnodet** [comment]
thanks!

**Comment by transitive-bullshit** [comment]
Updated: https://github.com/NotionX/react-notion-x/releases/tag/react-notion-x%407.0.1
