### ISSUE TITLE
Notion File uploads not working anymore - changed signed url approach

### ISSUE THREAD

**Issue by mfts** [NotionX/react-notion-x#576]
#### Description

I read a bunch about how signed urls are managed in Notion, but it seems that they changed their approach over the years. Especially recently all uploaded files are stored on their s3 storage and on download it creates a signed url. 

However, the current approach with react-notion-x isn't extracting the signed url. 
Perhaps I'm not sure how to enable it or find a solution. 

#### Notion Test Page ID

Here's an example page id: `12fd3f870f0080499b22f16d84dadd89`

#### Error message

Just getting a standard not authorized error from s3 when I try to download the file without the signed params:
https://prod-files-secure.s3.us-west-2.amazonaws.com/fc2e943e-e403-4068-b5f1-0096c54c3063/ff0da6e6-b954-4dfc-a684-8a00c10cc582/papermark-example-document.zip

**Comment by rimonhanna** [comment]
fixed in https://github.com/NotionX/react-notion-x/pull/455

**Comment by transitive-bullshit** [comment]
Merged #455 and released in https://github.com/NotionX/react-notion-x/releases/tag/react-notion-x%407.2.4

Let me know if you're still seeing issues && thanks 🙏

**Comment by wustep** [comment]
hmm I think this is leading to some side effects because of how we're appending `&spaceId` without checking if there's `?` first, and then this throws off a few things

https://github.com/NotionX/react-notion-x/issues/588
