### ISSUE TITLE
Error installing react-notion-x

### ISSUE THREAD

**Issue by antoniobrandao** [NotionX/react-notion-x#578]
I'm getting this error when installing `react-notion-x`

Tried with yarn, also with NPM. Tried with Node 22 and Node 23. 

This was in a Next.js project. Tried with both Next.js 14 and 15, always the same error.

Not sure if my report is very useful, I suppose it may not be possible for you to reproduce the error.

In any case, here's the error output:

--------

    node-pre-gyp info it worked if it ends with ok
    node-pre-gyp info using node-pre-gyp@1.0.11
    node-pre-gyp info using node@23.1.0 | darwin | arm64
    (node:9150) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v131-darwin-unknown-arm64.tar.gz
    node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v131-darwin-unknown-arm64.tar.gz
    node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@23.1.0 (node-v131 ABI, unknown) (falling back to source compile with node-gyp)
    node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v131-darwin-unknown-arm64.tar.gz
    gyp info it worked if it ends with ok
    gyp info using node-gyp@10.2.0
    gyp info using node@23.1.0 | darwin | arm64
    gyp info ok
    gyp info it worked if it ends with ok
    gyp info using node-gyp@10.2.0
    gyp info using node@23.1.0 | darwin | arm64
    gyp info find Python using Python version 3.9.6 found at \"/Applications/Xcode.app/Contents/Developer/usr/bin/python3\"

    (node:9347) ExperimentalWarning: CommonJS module /Users/antoniobrandao/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /Users/antoniobrandao/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/supports-color/index.js using require().
    Support for loading ES Module in require() is an experimental feature and might change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
    gyp http GET https://nodejs.org/download/release/v23.1.0/node-v23.1.0-headers.tar.gz
    gyp http 200 https://nodejs.org/download/release/v23.1.0/node-v23.1.0-headers.tar.gz
    gyp http GET https://nodejs.org/download/release/v23.1.0/SHASUMS256.txt
    gyp http 200 https://nodejs.org/download/release/v23.1.0/SHASUMS256.txt
    gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
    gyp info spawn args [
    gyp info spawn args '/Users/antoniobrandao/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args 'binding.gyp',
    gyp info spawn args '-f',
    gyp info spawn args 'make',
    gyp info spawn args '-I',
    gyp info spawn args '/Users/antoniobrandao/WEBROOT/genie/docsapp/node_modules/canvas/build/config.gypi',
    gyp info spawn args '-I',
    gyp info spawn args '/Users/antoniobrandao/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args '-I',
    gyp info spawn args '/Users/antoniobrandao/Library/Caches/node-gyp/23.1.0/include/node/common.gypi',
    gyp info spawn args '-Dlibrary=shared_library',
    gyp info spawn args '-Dvisibility=default',
    gyp info spawn args '-Dnode_root_dir=/Users/antoniobrandao/Library/Caches/node-gyp/23.1.0',
    gyp info spawn args '-Dnode_gyp_dir=/Users/antoniobrandao/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args '-Dnode_lib_file=/Users/antoniobrandao/Library/Caches/node-gyp/23.1.0/<(target_arch)/node.lib',
    gyp info spawn args '-Dmodule_root_dir=/Users/antoniobrandao/WEBROOT/genie/docsapp/node_modules/canvas',
    gyp info spawn args '-Dnode_engine=v8',
    gyp info spawn args '--depth=.',
    gyp info spawn args '--no-parallel',
    gyp info spawn args '--generator-output',
    gyp info spawn args 'build',
    gyp info spawn args '-Goutput_dir=.'
    gyp info spawn args ]
    /bin/sh: pkg-config: command not found
    gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
    gyp ERR! configure error
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack at ChildProcess.<anonymous> (/Users/antoniobrandao/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:317:18)
    gyp ERR! stack at ChildProcess.emit (node:events:507:28)
    gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    gyp ERR! System Darwin 23.6.0
    gyp ERR! command \"/Users/antoniobrandao/.nvm/versions/node/v23.1.0/bin/node\" \"/Users/antoniobrandao/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--update-binary\" \"--module=/Users/antoniobrandao/WEBROOT/genie/docsapp/node_modules/canvas/build/Release/canvas.node\" \"--module_name=canvas\" \"--module_path=/Users/antoniobrandao/WEBROOT/genie/docsapp/node_modules/canvas/build/Release\" \"--napi_version=9\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v131\"
    gyp ERR! cwd /Users/antoniobrandao/WEBROOT/genie/docsapp/node_modules/canvas
    gyp ERR! node -v v23.1.0
    gyp ERR! node-gyp -v v10.2.0
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute '/Users/antoniobrandao/.nvm/versions/node/v23.1.0/bin/node /Users/antoniobrandao/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/antoniobrandao/WEBROOT/genie/docsapp/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/antoniobrandao/WEBROOT/genie/docsapp/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v131' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/antoniobrandao/WEBROOT/genie/docsapp/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
    node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:507:28)
    node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1101:16)
    node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    node-pre-gyp ERR! System Darwin 23.6.0
    node-pre-gyp ERR! command \"/Users/antoniobrandao/.nvm/versions/node/v23.1.0/bin/node\" \"/Users/antoniobrandao/WEBROOT/genie/docsapp/node_modules/canvas/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\" \"--update-binary\"
    node-pre-gyp ERR! cwd /Users/antoniobrandao/WEBROOT/genie/docsapp/node_modules/canvas
    node-pre-gyp ERR! node -v v23.1.0
    node-pre-gyp ERR! node-pre-gyp -v v1.0.11
    node-pre-gyp ERR! not ok
    Failed to execute '/Users/antoniobrandao/.nvm/versions/node/v23.1.0/bin/node /Users/antoniobrandao/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/antoniobrandao/WEBROOT/genie/docsapp/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/antoniobrandao/WEBROOT/genie/docsapp/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v131' (1)"

**Comment by transitive-bullshit** [comment]
> CommonJS module /Users/antoniobrandao/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /Users/antoniobrandao/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/supports-color/index.js using require(). Support for loading ES Module in require() is an experimental feature and might change at any time

This line is an issue with Node.js 23's new ESM compat which is still a WIP from what I've seen. It should work with Node.js v22.

---

The other error you're seeing is that `canvas` is failing to install because of the optional dependency `react-pdf`. Check this repo for other users who're likely seeing a similar issue https://github.com/diegomura/react-pdf. What is the env you're using? This is really only necessary if you're using the PDF component, but right now it's marked as required.

**Comment by transitive-bullshit** [comment]
@antoniobrandao I just made `react-pdf` an optional dependency, so if it fails to install there shouldn't be any problems.

Just upgrade to latest https://github.com/NotionX/react-notion-x/releases/tag/react-notion-x%407.1.0

Note: `yarn@v1` is deprecated for all intents and purposes. I'd recommend using either `npm` or `pnpm`.

**Comment by transitive-bullshit** [comment]
If you're still having issues, please post the full install log along with detailed info about your environment.
