### ISSUE TITLE
Some tweets & images are not loading

### ISSUE THREAD

**Issue by wustep** [NotionX/react-notion-x#588]
#### Description
(repros in both `react-notion-x` and `nextjs-notion-starter-kit`)

#### Tweets

![CleanShot 2024-11-19 at 02 18 39@2x](https://github.com/user-attachments/assets/3a2ad058-3263-4881-89da-aab5608fa064)

![CleanShot 2024-11-19 at 01 04 02@2x](https://github.com/user-attachments/assets/39f892c3-dc38-4574-bf4d-9a33615309b4)

```
function Tweet({ id }: { id: string }) {
  const { recordMap } = useNotionContext()
  const tweet = (recordMap as types.ExtendedTweetRecordMap)?.tweets?.[id]

  return (
    <React.Suspense fallback={<TweetSkeleton />}>
      {tweet ? <EmbeddedTweet tweet={tweet} /> : <TweetNotFound />}
    </React.Suspense>
  )
}
```

This doesn't work, because `id` is actually `1772670594779079043&spaceId=30725683-e071-41f1-988d-e6e6fa72abd8`
but the recordMap stores `1772670594779079043` as the key.

Easy workaround is just to ignore the `&spaceId=...`

#### Images

Similarly, we see an issue with images as well -- see comments.

#### Notion Test Page ID
3b052104657a43feaf2230c2eb2a4036

**Comment by wustep** [comment]
Confirmed this fixes the issue locally, but I'm not sure this is the "right" fix!

![CleanShot 2024-11-19 at 02 18 08@2x](https://github.com/user-attachments/assets/05e469ac-a067-4608-8e74-ee4c5c74808a)

**Comment by wustep** [comment]
I'm noticing this is also why images are failing on my website -- 

![CleanShot 2024-11-19 at 02 38 01@2x](https://github.com/user-attachments/assets/d21093d2-22c0-42c4-9261-20102d1aca8f)

the spaceId is not correctly embedded in the URL, leading to issues when constructing the right image URL

![CleanShot 2024-11-19 at 02 38 24@2x](https://github.com/user-attachments/assets/fd98e797-aaa9-4fab-a87e-5b689932f2b9)

**Comment by wustep** [comment]
Oh, maybe from this &spaceId append?

https://github.com/NotionX/react-notion-x/blob/e3a1aefb59840a3cf40e5d23ae2ee2246b58b0cb/packages/react-notion-x/src/components/asset.tsx#L138

looking into..

**Comment by mfts** [comment]
Also broken on my end. Great investigative work @wustep

**Comment by transitive-bullshit** [comment]
Hopefully fixed in https://github.com/NotionX/react-notion-x/releases/tag/react-notion-x%407.2.5
