### ISSUE TITLE
SVG images are not loading with the latest release

### ISSUE THREAD

**Issue by MartinXPN** [NotionX/react-notion-x#589]
#### Description

Seems like the latest release does not render SVG images. I see a `404 (Not Found)` error in the console.

#### Notion Test Page ID

Here is a Notion page with a demo: https://martin-xpn.notion.site/Demo-7a15103d327f4c108a826ffcfd3f8373

P.S. Really happy to see the active work on this repo again. Thanks for the effort!

**Comment by MartinXPN** [comment]
#588 is probably related

**Comment by transitive-bullshit** [comment]
Can you try latest https://github.com/NotionX/react-notion-x/releases/tag/react-notion-x%407.2.5 and see if it's working now?

**Comment by MartinXPN** [comment]
Yeah, works like a charm. Thanks a lot @transitive-bullshit !
Closing the issue as the problem is resolved.
