### ISSUE TITLE
notion-client has the possibility of obtaining tables ?

### ISSUE THREAD

**Issue by markozxuu** [NotionX/react-notion-x#6]
Hi 👋 I'm building a blog and I think it would be a good option to structure it in table format. It allows me to put things like the publication date and the author.

I love the project ❤️

**Comment by transitive-bullshit** [comment]
Hey Markoz 👋 

Yes you can fetch table data using `react-notion-x`. There are two ways to do this.

1. Use [getPage](https://github.com/NotionX/react-notion-x/blob/master/docs/notion-client.notionapi.getpage.md) with a page that contains any collection view (including tables). This will fetch all table data as well which you can access via the result's `collection_query` property.
2. Use [getCollectionData](https://github.com/NotionX/react-notion-x/blob/master/docs/notion-client.notionapi.getcollectiondata.md) to fetch collection data for a given collection ID and table view ID. This is used by `getPage` under the hood.

Let me know if you have any specific questions about working with Notion's collection data. It's definitely the most complicated aspect of their API.

**Comment by markozxuu** [comment]
Thanks ! :D
