### ISSUE TITLE
How can I edit in collectionTableView

### ISSUE THREAD

**Issue by liangxiwei** [NotionX/react-notion-x#60]
I hava a share link which can edit when I share others. 
https://www.notion.so/database-78617effcc6941148c582686021d14d0

I add component in render like this.
`<NotionRenderer recordMap={recordMap} showTableOfContents={false} showCollectionViewDropdown={true} fullPage={true} darkMode={false} components={{
        equation: Equation,
        code: Code,
        collection: Collection,
        collectionRow: CollectionRow
      }} />`
And goto http://localhost:3000/database-78617effcc6941148c582686021d14d0

It will show collection view table,but can not edit.Is collection view table support edit?

**Comment by transitive-bullshit** [comment]
`react-notion-x` is strictly read-only. Editing is not supported at this time.

**Comment by georgescharlesbrain** [comment]
Is it still read-only?
Are you aware of any other notion database frontend with the editing capability?
