### ISSUE TITLE
Prop `className` did not match

### ISSUE THREAD

**Issue by whitedelay** [NotionX/react-notion-x#62]
Hello, thank you for your great project.

I have an issue.
I rendered my notion page using `react-notion-x` in my `next.js` project, and this error sometimes occurred.
```
Warning: Prop "className" did not match. Server: " language-bash" Client: "language-bash"
```

I found that the class name of code block has space at the front.
```
<pre class="notion-code language-bash">
  <code class=" language-bash">
```

Only `code` block has this issue. 
Do you know how to solve this problem?

**Comment by MichaelDevC** [comment]
I have the same error, still don't know how to solve it...

**Comment by remorses** [comment]
Reading other prismjs examples like this [one](https://github.com/satya164/react-simple-code-editor/blob/e5be544449a7ed0387a14236fff1c41bc6f0798f/src/index.js#L586) i think we can just skip adding the `landuage-{language}` classname, it looks like prism doesn't need that when using the `highlight` function

**Comment by transitive-bullshit** [comment]
The `Code` component has been updated to fix this issue in v6.
