### ISSUE TITLE
Compatibility with official Notion API

### ISSUE THREAD

**Issue by evaera** [NotionX/react-notion-x#66]
Is this library compatible with the official Notion API, which is now in public beta? If so, some examples on how to use it would be useful.

https://developers.notion.com/
https://developers.notion.com/reference/intro

**Comment by agcty** [comment]
+1 
Also looking for a way of using the official API!

**Comment by pedronauck** [comment]
+1

**Comment by Shunxu-H** [comment]
+1

**Comment by osbre** [comment]
I don't think that would be possible until Notion API adds support for more blocks, not just text-based blocks.

![sentence from the Notion docs about type "unsupported"](https://user-images.githubusercontent.com/23292709/135877759-3a2da2fd-726e-42e1-8f28-71b41837068b.png)

**Comment by Saroramath** [comment]
Did they really add the support to images? https://www.reddit.com/r/Notion/comments/p4gl35/notion_quietly_added_support_for_images_to_the_api/

**Comment by transitive-bullshit** [comment]
Definitely open to exploring this in the future via a compatibility layer like #228 

As things stand currently, see my answer here https://github.com/NotionX/react-notion-x/issues/92#issuecomment-964615906
