### ISSUE TITLE
Uploaded images are not rendering

### ISSUE THREAD

**Issue by pbteja1998** [NotionX/react-notion-x#68]
Hi, I am trying to use this package, but for some reason uploaded images look broken. Unsplash images and images added through links are working ok.

<img width="1440" alt="Screenshot 2021-05-16 at 10 12 02 AM" src="https://user-images.githubusercontent.com/17903466/118385742-545c8600-b62f-11eb-9120-65c632e43ba6.png">

Here when I right-click on the image and select `Open image in new tab`, the image is properly loading, but it is not being rendered on the actual page. Not sure if I am doing something wrong here. Any help with this would be very helpful.

These are the props that I added. Do I have to add anything else extra to these?
```jsx
 <NotionRenderer
  recordMap={extendedRecordMap}
  components={{
    code: Code,
    collection: Collection,
    collectionRow: CollectionRow,
    tweet: Tweet,
    pdf: Pdf,
    equation: Equation,
  }}
/>
```

**Comment by pbteja1998** [comment]
When I make the page public, the image seems to be rendered. Is it not possible without making it public?

Here is my current workflow:
— User has a notion page
— User gives me view access to that page
— I use my notion `token_v2` to fetch contents of that page and render it.

Will there be any problem in doing this like this? If not, is there a way to make images render by following this workflow, without making the page public?

**Comment by saidattax** [comment]
It could be a cross domain issue. What error does it say in the browser console? 

If it is that, you can solve it by using a proxy

**Comment by madooei** [comment]
@pbteja1998 you've closed the issue. Would you please note how you ended up solving it? I have the same problem. Thanks.

**Comment by pbteja1998** [comment]
@madooei I did not solve it. I ended up asking the users to make their page public.

**Comment by madooei** [comment]
@pbteja1998 would you consider opening this issue again? It might get an answer. Thanks.

PS. It seems some undocumented hand wavery is involved in getting this work (https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/lib/map-image-url.ts)

**Comment by MitchellRyrie-evanBuck** [comment]
@madooei @pbteja1998 hey
I built a website https://www.ryrie.ink/
I customized my avatar in my notification
And then I defined it in my project
![image]( https://github.com/user-attachments/assets/b06ddf53-9110-42a8-94ff-93c824d3c862 )
https://ryrie.ink/page-icon.jpg
Access is also normal
But I'm not sure why after deployment
![image]( https://github.com/user-attachments/assets/183979a5-3a3b-45ff-a5e4-adabcdda6e50 )
The image cannot be displayed and is also not available in the development environment
Only the icons built into Notion will be displayed

Customizing the upload cover is possible, but customizing the icon is not. My page is public, and I don't know why
