### ISSUE TITLE
Flag emojis missing on Windows 10

### ISSUE THREAD

**Issue by istvandesign** [NotionX/react-notion-x#69]
Hello and thanks for this great project,
I've found a small issue if you use flag emoji's and preview the build on Windows.

How to reproduce:  Use emoji flags in a notion document and preview on Windows 10. 

The issue can be reproduced here: 
https://istvan.design/#66c1fc59b57146aca26b4c0e9c6e0130

In Notion.so the emojis are automatically replaced with the ones from Mac OS, maybe there is a way to do this with a CDN and emoji svgs in this library ?

**Comment by MichaelDevC** [comment]
The emojis are from [Twemoji](https://twemoji.twitter.com/) a Twitter emojis system.
I figured out this problem by converting my entire page with [this package](https://www.npmjs.com/package/react-twemoji).

That's the simplified code to do the trick!
```js
<Twemoji options={{ className: 'twemoji' }}>
      <NotionRenderer/>
</Twemoji>  
```

Also, add some CSS to make the emojis size like the text size!
```css
img.twemoji {
  height: 1em;
  width: 1em;
  margin: 0 0.05em 0 0.1em;
  vertical-align: -0.1em;
}
```

**Comment by transitive-bullshit** [comment]
Thanks for the workaround @MichaelCasaDev.

**Comment by mnik01** [comment]
It has awful quality. Any ideas how to use SVG's instead of pngs?

**Comment by MichaelCasaDev** [comment]
@mnik01 
> It has awful quality. Any ideas how to use SVG's instead of pngs?

Use this, it will use SVGs images and lazy load all the emojis.
```jsx
  <Twemoji
    options={{
      className: "twemoji",
      size: "svg",
      ext: ".svg",
      attributes: () => {
        return {
          rel: "preload",
          loading: "lazy",
          decoding: "sync",
        };
      },
    }}
  >
```

**Comment by mnik01** [comment]
@MichaelCasaDev 
Thank you so much
LGTM
