### ISSUE TITLE
Unversioned requests will no longer be accepted on June 1, 2021

### ISSUE THREAD

**Issue by pbteja1998** [NotionX/react-notion-x#70]
Not sure if this affects anything in `react-notion-x`. Just wanted to share it, in case it's applicable. 

https://developers.notion.com/changelog/unversioned-requests-no-longer-accepted

**Comment by transitive-bullshit** [comment]
Thanks @pbteja1998, this will definitely affect `react-notion-x`.

**Comment by hckhanh** [comment]
Hi @transitive-bullshit,
Is there any plan to work on it?

**Comment by pbteja1998** [comment]
Seems like this did not affect anything for the private apu that is being used here. Closing this.
