### ISSUE TITLE
Easy way to get table data 

### ISSUE THREAD

**Issue by ddanielcruzz** [NotionX/react-notion-x#79]
I already read other issues asking similar questions, and from what I understand I would need to search for the data I want and modify it myself, or am I wrong? 

My goal is the get data in this format https://notion-api.splitbee.io/v1/table/20720198ca7a4e1b92af0a007d3b45a4. 😄

**Comment by transitive-bullshit** [comment]
At least for now, I would recommend using Notion's official API for this use case.

This is definitely an area where Notion's unofficial API (which react-notion-x wraps) provides the data in a cumbersome and overly normalized format which makes it difficult to use outside of using it with the provided react renderer.

I'd love to improve this in the future.

**Comment by ddanielcruzz** [comment]
Thanks for the quick response! I guess I'll use `notion-api-worker` to get the table data and `notion-client` to get all page's blocks. 

Another question I have is, how can I render images from a private page? I'm trying the following 

```js
const notion = new NotionAPI({
  authToken: myNotionV2token,
});
...
const recordMap = await notion.getPage(postId);

...
<NotionRenderer recordMap={recordMap} />
```

Some context: 
 - I'm using the token mentioned [here](https://github.com/splitbee/notion-api-worker#receiving-the-token)
 - If I try to log `recordMap.signed_urls` I get an empty object.
- I already checked that my token works by making a GET request to the image URL and passing it as a cookie header.
 
I'd really appreciate the help 😬

**Comment by ddanielcruzz** [comment]
Update: 

The problem is that to get images from private spaces you need to pass your `token_v2` in the request as Cookie header. 

I solved this by using a Cloudfare Worker. In short what I do is: 
1. Replace the `mapImageUrl` function of the renderer and there I call my worker passing the Notion image URL as an argument
2. My worker makes the request to that URL with the token and returns the data from it and that's what is rendered.
