### ISSUE TITLE
Setting fullPage={true} breaks mobile rendering

### ISSUE THREAD

**Issue by tiivik** [NotionX/react-notion-x#8]
Setting fullPage to true `<NotionRenderer recordMap={recordMap} fullPage={true}  />` makes it unable to scroll the rendered pages on mobile. The same can be observed on the demo site https://demo.notionx.so/, see screenshot captured on iPhone 7 below
![IMG_6B2C00006F3F-1](https://user-images.githubusercontent.com/14925757/98991648-d19a2780-2534-11eb-8936-6401bbb2deec.jpeg)
 
Setting fullPage to false allows mobile scrolling, but obviously loses the icon and header image.

**Comment by transitive-bullshit** [comment]
I am unable to reproduce this issue either on my iPhone X or in any of Chrome / Safari's mobile emulators.

If anyone else is able to provide a reproducible version of this issue, please let me know.
