### ISSUE TITLE
Is the HTML class including the Notion page ID necessary?

### ISSUE THREAD

**Issue by mcintyre94** [NotionX/react-notion-x#84]
I'm exploring whether it's possible to provide a Notion sharing service that obfuscates the original Notion page IDs to a reasonable extent - reducing the impact of the page needing to be made public (until we can use the official API). It looks like the only place the Notion page ID slips into the rendered content is the top-level div, which is eg. `notion notion-app light-mode notion-block-067dd719a912471ea9a3ac10710e7fdf`. I can't see any CSS or anything using the class `notion-block-067dd719a912471ea9a3ac10710e7fdf`.

Is this class with the page ID necessary, and if not then would you accept a PR that either removed it or added a prop to do so?

**Comment by saidattax** [comment]
I would suggest you fork the repo and update it to your preferences for edge cases like this
