### ISSUE TITLE
Can you share development guidelines?

### ISSUE THREAD

**Issue by mcintyre94** [NotionX/react-notion-x#85]
I'd like to contribute to this library but I'm having trouble getting it running locally with `npm link`. Could you share some guidelines on how you get this working? This is what I've tried:

- Fork the repo + clone locally
- `yarn build`
- cd `packages/react-notion-x`
- `npm link`

In my project that uses react-notion-x:

- `npm link "react-notion-x"

I get an error message `Module not found: Can't resolve 'react-notion-x'` when my project tries to use `react-notion-x`. If I include the global CSS then I get `Module not found: Can't resolve 'react-notion-x/src/styles.css'`.

My guess is that there's something I'm not doing right to deal with the multiple package structure? Any help would be appreciated!

**Comment by saidattax** [comment]
I'm using a similar setup already. 

After doing `npm link` did you get a confirmation message in your log that it indeed linked correctly?

Also, I did it a bit differently in my personal project folder

* `npm i -S react-notion-x` (this will add react-notion-x to `package.json` in your personal project)
* `npm link react-notion-x` (this will link the react-notion-x folder in your `node_modules` to your local react-notion-x)

**Comment by ddanielcruzz** [comment]
I think you need to do the linking via lerna, like `lerna exec --npm link`

**Comment by mcintyre94** [comment]
Thanks both! In case it helps anyone, this is how I got it working:

- Note: Using npm 12.22.1. I tried npm 14 (using nvm) and npm link didn't work. Probably user error, maybe an npm bug but seems unlikely. Will need to look more into this!

- Fork the repo + clone locally (in my case to ~/projects/react-notion-x)

In the `react-notion-x` clone directory, record an npm link for react-notion-x:

```bash
# ~/projects/react-notion-x
$ yarn build
$ cd packages/react-notion-x
$ npm link
~/.nvm/versions/node/v12.22.1/lib/node_modules/react-notion-x -> ~/projects/react-notion-x/packages/react-notion-x
```

In my project directory, use that link:

```bash
# ~/projects/sendy
$ npm install react-notion-x
$ npm link react-notion-x
~/projects/sendy/node_modules/react-notion-x -> ~/.nvm/versions/node/v12.22.1/lib/node_modules/react-notion-x -> ~/projects/react-notion-x/packages/react-notion-x
```

Now when I load a page it uses the `react-notion-x` locally, but there's a hooks error pointing at https://reactjs.org/warnings/invalid-hook-call-warning.html . As that page says, "This problem can also come up when you use npm link or an equivalent."

Still in my project directory, record links in the same way as before to react and react-dom in the project's node_modules

```bash
# ~/projects/sendy
$ cd node_modules/react
$ npm link
...
~/.nvm/versions/node/v12.22.1/lib/node_modules/react -> ~/projects/sendy/node_modules/react
$ cd ../react-dom
$ npm link
...
~/.nvm/versions/node/v12.22.1/lib/node_modules/react-dom -> ~/projects/sendy/node_modules/react-dom
```

Back in the `react-notion-x` clone directory, use those links in the same way that the project uses react-notion-x:

```bash
# ~/projects/react-notion-x
$ npm link react
~/projects/react-notion-x/packages/react-notion-x/node_modules/react -> ~/.nvm/versions/node/v12.22.1/lib/node_modules/react -> ~/projects/react-notion-x-test/node_modules/react
$ npm link react-dom
~/projects/react-notion-x/packages/react-notion-x/node_modules/react-dom -> ~/.nvm/versions/node/v12.22.1/lib/node_modules/react-dom -> ~/projects/react-notion-x-test/node_modules/react-dom
```

And voila, it works! Now to test a change to the code locally, change it in `~/projects/react-notion-x` and then run `yarn build` there. The `react-notion-x` in the project's node_modules will pick up those changes immediately.

**Comment by transitive-bullshit** [comment]
https://github.com/NotionX/react-notion-x/blob/master/contributing.md
