### ISSUE TITLE
Any plan support transclusion_container block type?

### ISSUE THREAD

**Issue by ysjiang4869** [NotionX/react-notion-x#90]
Notion add new  synced blok, which is  transclusion_container and transclusion_reference type.
Any plan to support new type?

**Comment by normdoow** [comment]
Yes, I am working on adding this now. Hoping to be done in the next couple of days.

**Comment by transitive-bullshit** [comment]
See https://github.com/NotionX/react-notion-x/pull/91 by @normdoow
