### ISSUE TITLE
How to use this with official Notion API?

### ISSUE THREAD

**Issue by agcty** [NotionX/react-notion-x#92]
Is this even possible?

This is my minimal code:

```jsx
import { NotionRenderer } from "react-notion-x";

import notion from "@api/notion";

export default function Test({ data }) {
  return (
    <div>
      <div>{JSON.stringify(data)} </div>

      <NotionRenderer recordMap={data} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const result = await notion.blocks.children.list({
    block_id: "c84a83a3751e4d30abcf5759d582720b",
  });

  // const result = await notion.databases.query(});

  return {
    props: { data: result }, // will be passed to the page component as props
  };
}

```

The data is fetched just fine from the api but it is not displayed in any way. I always get this error:

![image](https://user-images.githubusercontent.com/12101091/122636551-2664d880-d0ea-11eb-9936-f2b5b3358897.png)

Even though the data is definitely not null, seems like it looks for a nested property that might be null.

**Comment by kyashrathore** [comment]
Official is unusable as of now, it returns very basic blocks like text.

Image, embed, blockquote, callout which are at minimum required for content pages are still unsupported.

**Comment by agcty** [comment]
@kyashrathore ah thank you for the clarification!

**Comment by bogusz-pekalski** [comment]
@kyashrathore Hey! How about now? :) Do you plan working with official API?

**Comment by transitive-bullshit** [comment]
As @kyashrathore commented, it's not currently possible because Notion's public API doesn't expose most block information, so most notion content can't be rendered from their publicly-supported APIs. Their API is meant more for data / collection-related use cases, at least for the time being.

**Comment by transitive-bullshit** [comment]
See also #66
