### ISSUE TITLE
Search Broken

### ISSUE THREAD

**Issue by MichaelDevC** [NotionX/react-notion-x#97]
After the new update to '4.7.5' (8b15ca4cfe12e587099c813152adc10af1876180) with the new search method that return the correct recordMap i can't use the search dialog.
It returns to me that error

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/57275048/123622212-43955780-d80c-11eb-92d4-a7d84d34acf4.png">

**Comment by transitive-bullshit** [comment]
This has been fixed in v6.
